// =============================================================
// Sheng Dictionary — Seed File v3 (Mega Batch — 300+ words)
// =============================================================
// NEW words only — not in seed.ts or seed-v2.ts
// Usage: Add to package.json: "seed:v3": "tsx scripts/seed-v3.ts"
// Run:   pnpm seed:v3
// =============================================================

import mongoose from "mongoose";
import dotenv from "dotenv";
import path from "path";

dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

const definitionSchema = new mongoose.Schema({
  meaning: String,
  example: String,
  addedBy: { type: String, default: "seed" },
});

const wordSchema = new mongoose.Schema(
  {
    word: { type: String, required: true, unique: true, lowercase: true, trim: true },
    slug: { type: String, required: true, unique: true, lowercase: true, trim: true },
    definitions: [definitionSchema],
    partOfSpeech: {
      type: String,
      enum: ["noun", "verb", "adjective", "expression", "adverb"],
      default: "noun",
    },
    origin: String,
    relatedWords: [String],
    region: { type: String, default: "Nationwide" },
    status: { type: String, enum: ["pending", "approved", "rejected"], default: "approved" },
    viewCount: { type: Number, default: 0 },
    isFeatured: { type: Boolean, default: true },
    tags: [String],
    submittedBy: { type: String, default: "seed" },
  },
  { timestamps: true }
);

const Word = mongoose.models.Word || mongoose.model("Word", wordSchema);

const words = [

  // ══════════════════════════════════════════════
  // PEOPLE & RELATIONSHIPS
  // ══════════════════════════════════════════════
  {
    word: "morio",
    slug: "morio",
    definitions: [{ meaning: "A male friend / best friend / homie", example: "Morio wa mine alinisort bila kusita." }],
    partOfSpeech: "noun",
    origin: "Popularised by Wakadinali in 'Morio Anzenza'",
    tags: ["people", "friends"],
    relatedWords: ["msee", "mtu"],
  },
  {
    word: "morio-anzenza",
    slug: "morio-anzenza",
    definitions: [{ meaning: "A friend since day one / original day-one homie", example: "Huyu ni morio anzenza, tumekuwa pamoja since mtaani." }],
    partOfSpeech: "expression",
    origin: "Popularised by Wakadinali song 'Morio Anzenza'",
    tags: ["people", "friends", "loyalty"],
  },
  {
    word: "buda",
    slug: "buda",
    definitions: [{ meaning: "Father / dad / also used informally to address any man", example: "Buda wangu aliniambia nikuje nyumbani." }],
    partOfSpeech: "noun",
    tags: ["people", "family"],
    relatedWords: ["budha", "mzee", "mathe"],
  },
  {
    word: "budha",
    slug: "budha",
    definitions: [{ meaning: "Father / old man", example: "Budha wake ni msee wa heshima sana." }],
    partOfSpeech: "noun",
    tags: ["people", "family"],
    relatedWords: ["buda", "mzee"],
  },
  {
    word: "mziza",
    slug: "mziza",
    definitions: [{ meaning: "A parent / mother or father", example: "Mziza wangu ndiye amenisort sana maishani." }],
    partOfSpeech: "noun",
    origin: "From Swahili 'mzazi' meaning parent; popularised by Scar Mkadinali of Wakadinali",
    tags: ["people", "family"],
    relatedWords: ["mathe", "mokoro", "buda"],
  },
  {
    word: "siz",
    slug: "siz",
    definitions: [{ meaning: "Sister", example: "Siz yangu amefika, wacha tumwambie habari." }],
    partOfSpeech: "noun",
    origin: "From English 'sis'",
    tags: ["people", "family"],
  },
  {
    word: "pikini",
    slug: "pikini",
    definitions: [{ meaning: "Children / kids", example: "Pikini wa mtaani wanacheza kwa uwanja." }],
    partOfSpeech: "noun",
    origin: "From Pidgin English 'pickin' meaning small child",
    tags: ["people", "family"],
  },
  {
    word: "mvu",
    slug: "mvu",
    definitions: [{ meaning: "A young man / boy", example: "Mvu yule ni msafi, anaenda vizuri maishani." }],
    partOfSpeech: "noun",
    tags: ["people", "youth"],
  },
  {
    word: "manzi",
    slug: "manzi",
    definitions: [{ meaning: "A girl / girlfriend", example: "Manzi wangu ni wa Eastlands, tuko sawa." }],
    partOfSpeech: "noun",
    tags: ["people", "girls", "relationships"],
    relatedWords: ["dem", "denge", "mshothre"],
  },
  {
    word: "mpoa",
    slug: "mpoa",
    definitions: [{ meaning: "A cute / attractive girl", example: "Mpoa yule kwa stage anafanya watu wote waangalie." }],
    partOfSpeech: "noun",
    tags: ["people", "girls", "compliment"],
  },
  {
    word: "riambez",
    slug: "riambez",
    definitions: [{ meaning: "A cute girl / a beautiful woman", example: "Riambez yule ni wa kweli, amevaa vizuri." }],
    partOfSpeech: "noun",
    tags: ["people", "girls", "compliment"],
    relatedWords: ["mpoa", "mrembo"],
  },
  {
    word: "supu",
    slug: "supu",
    definitions: [{ meaning: "A beautiful woman or girl / a gem / something exceptional", example: "Supu wangu ni wa mwisho, hawezi badilishwa." }],
    partOfSpeech: "noun",
    origin: "From Swahili 'soup' — something rich and warm",
    tags: ["people", "girls", "compliment"],
  },
  {
    word: "msupa",
    slug: "msupa",
    definitions: [{ meaning: "A beautiful / attractive woman", example: "Msupa yule kwa ofisi amevaa vizuri leo." }],
    partOfSpeech: "noun",
    tags: ["people", "girls", "compliment"],
    relatedWords: ["supu", "riambez", "mpoa"],
  },
  {
    word: "momiz",
    slug: "momiz",
    definitions: [{ meaning: "A girl / girlfriend", example: "Momiz wangu alinipiga simu usiku kucha." }],
    partOfSpeech: "noun",
    tags: ["people", "girls", "relationships"],
  },
  {
    word: "klande",
    slug: "klande",
    definitions: [{ meaning: "A secret lover / side piece / someone having an affair", example: "Alishikwa na klande wake, mambo yakawa ngumu." }],
    partOfSpeech: "noun",
    tags: ["relationships", "people"],
  },
  {
    word: "baruta",
    slug: "baruta",
    definitions: [{ meaning: "A promiscuous woman", example: "Wacha stori za baruta, tafuta mtu wa kweli." }],
    partOfSpeech: "noun",
    tags: ["people", "relationships", "negative"],
  },
  {
    word: "poko",
    slug: "poko",
    definitions: [{ meaning: "A prostitute / sex worker", example: "Sehemu ile ni ya poko, usikwame usiku." }],
    partOfSpeech: "noun",
    tags: ["people", "negative"],
  },
  {
    word: "lele",
    slug: "lele",
    definitions: [{ meaning: "A lesbian / homosexual woman", example: "Hadithi yake ni yake, wachana na lele matters." }],
    partOfSpeech: "noun",
    tags: ["people", "LGBTQ"],
  },
  {
    word: "bazu",
    slug: "bazu",
    definitions: [{ meaning: "A big man / a respected figure / kingpin", example: "Bazu wa mtaani anaenda, watu wote wanasimama." }],
    partOfSpeech: "noun",
    tags: ["people", "respect", "leadership"],
    relatedWords: ["bazenga", "sonko", "donga"],
  },
  {
    word: "bazenga",
    slug: "bazenga",
    definitions: [{ meaning: "A respected and liked person / someone special", example: "Bazenga wa eneo amefika, watu wanafurahi." }],
    partOfSpeech: "noun",
    tags: ["people", "respect"],
    relatedWords: ["bazu", "sonko"],
  },
  {
    word: "sonko",
    slug: "sonko",
    definitions: [{ meaning: "A rich person / wealthy person / boss", example: "Sonko wa block anasort watu chakula." }],
    partOfSpeech: "noun",
    tags: ["people", "money", "respect"],
    relatedWords: ["bazu", "donga"],
  },
  {
    word: "donga",
    slug: "donga",
    definitions: [{ meaning: "A boss / CEO / someone in charge", example: "Donga wa kampuni ataenda meeting asubuhi." }],
    partOfSpeech: "noun",
    tags: ["people", "leadership", "work"],
    relatedWords: ["sonko", "bazu"],
  },
  {
    word: "fathe",
    slug: "fathe",
    definitions: [{ meaning: "A respected elder / godfather figure", example: "Fathe wa mtaa amesort mambo, sasa kuna amani." }],
    partOfSpeech: "noun",
    tags: ["people", "respect"],
    relatedWords: ["bazu"],
  },
  {
    word: "mnisa",
    slug: "mnisa",
    definitions: [{ meaning: "An artist / musician / creative person", example: "Mnisa yule ameingia studio wiki hii." }],
    partOfSpeech: "noun",
    origin: "Popularised by ThirtyFourBrick",
    tags: ["people", "music", "art"],
  },
  {
    word: "mkuu",
    slug: "mkuu",
    definitions: [{ meaning: "A leader / respected influential person", example: "Mkuu wa genge anaongea, wote wanyamaze." }],
    partOfSpeech: "noun",
    origin: "From Swahili 'mkuu' meaning great/leader",
    tags: ["people", "respect", "leadership"],
  },
  {
    word: "babii",
    slug: "babii",
    definitions: [{ meaning: "A person from posh/rich areas / a softie who hasn't seen street life", example: "Babii yule hajui street life, ni wa Kilimani." }],
    partOfSpeech: "noun",
    tags: ["people", "class"],
    region: "Nairobi",
    relatedWords: ["mbabi"],
  },
  {
    word: "mbabi",
    slug: "mbabi",
    definitions: [{ meaning: "Someone from a posh area / a rich uptown person", example: "Mbabi yule hakujua hata mathree ni nini." }],
    partOfSpeech: "noun",
    tags: ["people", "class"],
    region: "Nairobi",
    relatedWords: ["babii"],
  },
  {
    word: "kadinya",
    slug: "kadinya",
    definitions: [{ meaning: "An irritating fool / someone addicted to sex", example: "Kadinya yule anaumiza watu kila siku." }],
    partOfSpeech: "noun",
    tags: ["people", "insult"],
  },
  {
    word: "mbleina",
    slug: "mbleina",
    definitions: [{ meaning: "Someone absent-minded / a traitor / someone who knows nothing", example: "Mbleina yule aliuza wenzake kwa bei ya chini." }],
    partOfSpeech: "noun",
    tags: ["people", "insult", "negative"],
    relatedWords: ["mrazi"],
  },
  {
    word: "mrazi",
    slug: "mrazi",
    definitions: [{ meaning: "A traitor / someone who leaks secrets / a snitch", example: "Mrazi ndiye alimshow karao, tulijua." }],
    partOfSpeech: "noun",
    tags: ["people", "negative", "betrayal"],
    relatedWords: ["mbleina", "mtiaji"],
  },
  {
    word: "mtiaji",
    slug: "mtiaji",
    definitions: [{ meaning: "A snitch / a hater / someone who makes fun of everything", example: "Mtiaji wa class alifanya sereche kwa headmaster." }],
    partOfSpeech: "noun",
    tags: ["people", "negative", "school"],
    relatedWords: ["mrazi"],
  },
  {
    word: "manambling",
    slug: "manambling",
    definitions: [{ meaning: "Haters / a group of haters", example: "Manambling wangu hawanisimamishi, ninasonga mbele." }],
    partOfSpeech: "noun",
    tags: ["people", "negative", "haters"],
  },
  {
    word: "taliban",
    slug: "taliban",
    definitions: [{ meaning: "Someone who causes violence / an aggressive person", example: "Taliban wa block yetu ni hatari usiku." }],
    partOfSpeech: "noun",
    tags: ["people", "violence", "street"],
    region: "Nairobi",
  },
  {
    word: "murife",
    slug: "murife",
    definitions: [{ meaning: "Someone who never settles in one place / a wanderer", example: "Murife yule hajui makazi, leo hapa kesho pale." }],
    partOfSpeech: "noun",
    tags: ["people", "lifestyle"],
  },
  {
    word: "elchapo",
    slug: "elchapo",
    definitions: [{ meaning: "An extraordinary person / someone exceptional", example: "Elchapo wa game yetu hakuna — yeye peke yake anaweza." }],
    partOfSpeech: "noun",
    origin: "Named after Mexican cartel boss El Chapo — someone untouchable",
    tags: ["people", "compliment", "genz"],
  },
  {
    word: "dingo",
    slug: "dingo",
    definitions: [{ meaning: "A thief / a robber", example: "Dingo aliibia msee simu kwa stage leo." }],
    partOfSpeech: "noun",
    tags: ["crime", "people"],
    relatedWords: ["regre", "pinji"],
  },

  // ══════════════════════════════════════════════
  // GREETINGS & EVERYDAY EXPRESSIONS
  // ══════════════════════════════════════════════
  {
    word: "niaje",
    slug: "niaje",
    definitions: [{ meaning: "How are you? / What's up? / How is it?", example: "Niaje msee, mambo vipi?" }],
    partOfSpeech: "expression",
    origin: "Corruption of Swahili 'ni viaje?' meaning 'how is it?'",
    tags: ["greetings", "everyday"],
    relatedWords: ["sasa", "rada", "riang"],
  },
  {
    word: "mambo",
    slug: "mambo",
    definitions: [{ meaning: "What's up? / How are things? / a common greeting", example: "Mambo vipi, umefanya nini leo?" }],
    partOfSpeech: "expression",
    origin: "Swahili for 'matters/things' repurposed as a greeting",
    tags: ["greetings", "everyday"],
    relatedWords: ["niaje", "sasa"],
  },
  {
    word: "vipi",
    slug: "vipi",
    definitions: [{ meaning: "How? / How are things going?", example: "Vipi gani, mambo imekuwa aje?" }],
    partOfSpeech: "expression",
    tags: ["greetings", "everyday"],
  },
  {
    word: "riang",
    slug: "riang",
    definitions: [{ meaning: "What's up? / What's going on?", example: "Riang bro, umefanya nini usiku huu?" }],
    partOfSpeech: "expression",
    tags: ["greetings", "everyday"],
    relatedWords: ["rada", "niaje", "mambo"],
  },
  {
    word: "manze",
    slug: "manze",
    definitions: [{ meaning: "Man / dude / used to start or continue a story / expression of surprise", example: "Manze jo, hukuona ile ilikuwa mbaya?" }],
    partOfSpeech: "expression",
    tags: ["greetings", "everyday", "expression"],
  },
  {
    word: "oyaa",
    slug: "oyaa",
    definitions: [{ meaning: "Hey you / used to call someone whose name you don't know", example: "Oyaa, ngoja kidogo, tuongee." }],
    partOfSpeech: "expression",
    tags: ["greetings", "everyday"],
  },
  {
    word: "cuzo",
    slug: "cuzo",
    definitions: [{ meaning: "A term to start a friendly conversation / hey cousin / bro", example: "Cuzo nishow, ile mpya ya Wakadinali iko form?" }],
    partOfSpeech: "expression",
    tags: ["greetings", "friends"],
  },
  {
    word: "ati",
    slug: "ati",
    definitions: [{ meaning: "What? / allegedly / supposedly — used to relay gossip or question something", example: "Ati alipata baby, kweli?" }],
    partOfSpeech: "expression",
    tags: ["expression", "everyday"],
  },
  {
    word: "bora-uhai",
    slug: "bora-uhai",
    definitions: [{ meaning: "Nothing matters as long as you're alive / life goes on / oh well", example: "Nilipoteza kazi lakini bora uhai, tutajaribu tena." }],
    partOfSpeech: "expression",
    tags: ["expression", "philosophy", "resilience"],
  },
  {
    word: "poa",
    slug: "poa",
    definitions: [{ meaning: "Cool / okay / fine / good", example: "Mambo? Poa kabisa, hakuna shida." }],
    partOfSpeech: "adjective",
    tags: ["greetings", "everyday", "compliment"],
  },
  {
    word: "noma-sana",
    slug: "noma-sana",
    definitions: [{ meaning: "Very serious / very bad / extreme", example: "Hali ya barabara ni noma sana leo, gari nyingi." }],
    partOfSpeech: "expression",
    tags: ["expression", "emphasis"],
  },
  {
    word: "kwani-ni-kesho",
    slug: "kwani-ni-kesho",
    definitions: [{ meaning: "Why wait? / This can't wait until tomorrow / do it now", example: "Kwani ni kesho? Fanya saa hii!" }],
    partOfSpeech: "expression",
    origin: "Popularised by Buruklyn Boyz",
    tags: ["expression", "urgency"],
  },
  {
    word: "bant",
    slug: "bant",
    definitions: [{ meaning: "To make a mistake / to mess up / to slip up", example: "Umebant sana, hukufaa kusema hivyo." }],
    partOfSpeech: "verb",
    tags: ["expression", "mistakes"],
  },
  {
    word: "riswa",
    slug: "riswa",
    definitions: [{ meaning: "A curse / used to curse something unknown or unfamiliar", example: "Riswa! Gari imeniangusha tena leo." }],
    partOfSpeech: "expression",
    tags: ["expression", "curse"],
  },
  {
    word: "woiyee",
    slug: "woiyee",
    definitions: [{ meaning: "Expression of sympathy / oh no / shame / poor thing", example: "Woiyee, alipoteza kazi na watoto wake wana njaa." }],
    partOfSpeech: "expression",
    tags: ["expression", "sympathy", "emotions"],
  },
  {
    word: "form",
    slug: "form",
    definitions: [{ meaning: "Connections / what's happening / asking what's up / to have a plan", example: "Una form ya kitu leo usiku?" }],
    partOfSpeech: "noun",
    tags: ["expression", "everyday", "plans"],
  },
  {
    word: "uradi",
    slug: "uradi",
    definitions: [{ meaning: "Something interesting / the way forward / a good plan or connect", example: "Nishow uradi, una deal gani?" }],
    partOfSpeech: "noun",
    tags: ["expression", "plans", "opportunity"],
  },
  {
    word: "kasongo",
    slug: "kasongo",
    definitions: [{ meaning: "A Gen Z term — often used to mean 'okay' or reference something uncertain", example: "Kasongo, tutaona." }],
    partOfSpeech: "expression",
    origin: "Created by Gen Z Nairobi youth",
    tags: ["expression", "genz"],
  },
  {
    word: "kitawaramba",
    slug: "kitawaramba",
    definitions: [{ meaning: "It will backfire on you / karma is coming / you'll regret it", example: "Ukifanya mtu hivyo kitawaramba, subiri tu." }],
    partOfSpeech: "expression",
    origin: "Went viral after the Shakahola massacre coverage in 2023",
    tags: ["expression", "warning", "karma"],
  },
  {
    word: "wantam",
    slug: "wantam",
    definitions: [{ meaning: "One term / in one go / just one shot", example: "Fanya kazi wantam, usichoke njiani." }],
    partOfSpeech: "expression",
    origin: "Popularised during the DCP political party by Riggy G",
    tags: ["expression", "politics", "genz"],
  },
  {
    word: "siku-zombo",
    slug: "siku-zombo",
    definitions: [{ meaning: "Every day / daily / all the time", example: "Anafanya kazi siku zombo bila kupumzika." }],
    partOfSpeech: "expression",
    origin: "Popularised by Mziza Family in 'Ni God siku zombo'",
    tags: ["expression", "time"],
  },
  {
    word: "mabeshte",
    slug: "mabeshte",
    definitions: [{ meaning: "Close friends / best friends / squad", example: "Mabeshte zangu wote tutakutana weekend hii." }],
    partOfSpeech: "noun",
    tags: ["people", "friends"],
    relatedWords: ["mbogi", "morio"],
  },
  {
    word: "kimonyoski",
    slug: "kimonyoski",
    definitions: [{ meaning: "A group of people with a common interest / clique / circle", example: "Kimonyoski chetu kinaenda concert wiki hii." }],
    partOfSpeech: "noun",
    tags: ["people", "groups"],
    relatedWords: ["mbogi"],
  },
  {
    word: "mbogi",
    slug: "mbogi",
    definitions: [{ meaning: "A group / crew / gang / squad", example: "Mbogi yangu yote iko hapo, twende." }],
    partOfSpeech: "noun",
    tags: ["people", "groups"],
    relatedWords: ["kimonyoski"],
  },
  {
    word: "kirende",
    slug: "kirende",
    definitions: [{ meaning: "A big crowd / multitude / a large group of people", example: "Kirende ya watu ilitoka kwa Stadium." }],
    partOfSpeech: "noun",
    origin: "From Kikuyu; popularised by Spider Clan in 2023",
    tags: ["people", "groups"],
  },

  // ══════════════════════════════════════════════
  // MONEY & NUMBERS
  // ══════════════════════════════════════════════
  {
    word: "thao",
    slug: "thao",
    definitions: [{ meaning: "One thousand shillings (Ksh 1,000)", example: "Naomba thao moja kukamilisha fare." }],
    partOfSpeech: "noun",
    tags: ["money", "numbers"],
    relatedWords: ["ganji", "chapaa"],
  },
  {
    word: "punch",
    slug: "punch",
    definitions: [{ meaning: "Five hundred shillings (Ksh 500)", example: "Punch inaweza ingia jioni kwa chakula na fare." }],
    partOfSpeech: "noun",
    tags: ["money", "numbers"],
    relatedWords: ["thao"],
  },
  {
    word: "kioo",
    slug: "kioo",
    definitions: [{ meaning: "One hundred shillings (Ksh 100)", example: "Toa kioo tuoneshe, chakula kinaisha." }],
    partOfSpeech: "noun",
    origin: "Swahili for 'mirror' — the Ksh 100 coin is shiny",
    tags: ["money", "numbers"],
    relatedWords: ["soo", "jongo"],
  },
  {
    word: "jongo",
    slug: "jongo",
    definitions: [{ meaning: "One hundred shillings (Ksh 100) / a hundred bob", example: "Nitakupa jongo ukisort hii kitu." }],
    partOfSpeech: "noun",
    tags: ["money", "numbers"],
    relatedWords: ["kioo", "soo"],
  },
  {
    word: "soo",
    slug: "soo",
    definitions: [{ meaning: "One hundred shillings (Ksh 100)", example: "Soo moja inatosha kwa githeri na soda." }],
    partOfSpeech: "noun",
    tags: ["money", "numbers"],
    relatedWords: ["kioo", "jongo"],
  },
  {
    word: "mbao",
    slug: "mbao",
    definitions: [{ meaning: "Twenty shillings (Ksh 20)", example: "Niomba mbao tu, naendelea." }],
    partOfSpeech: "noun",
    tags: ["money", "numbers"],
  },
  {
    word: "kinde",
    slug: "kinde",
    definitions: [{ meaning: "Ten shillings (Ksh 10)", example: "Kinde ya fare imeniisha, nitembee miguu." }],
    partOfSpeech: "noun",
    tags: ["money", "numbers"],
    relatedWords: ["ashu"],
  },
  {
    word: "ashu",
    slug: "ashu",
    definitions: [{ meaning: "Ten shillings (Ksh 10)", example: "Ashu tu ndiyo imebaki mfukoni." }],
    partOfSpeech: "noun",
    tags: ["money", "numbers"],
    relatedWords: ["kinde"],
  },
  {
    word: "kobole",
    slug: "kobole",
    definitions: [{ meaning: "Five shillings (Ksh 5) / small change / coins", example: "Kobole tu ndizo zimebaki baada ya kulipa." }],
    partOfSpeech: "noun",
    tags: ["money", "numbers"],
  },
  {
    word: "finje",
    slug: "finje",
    definitions: [{ meaning: "Fifty shillings (Ksh 50)", example: "Finje moja inaweza nunua mahindi ya moto." }],
    partOfSpeech: "noun",
    tags: ["money", "numbers"],
    relatedWords: ["chuani"],
  },
  {
    word: "doh",
    slug: "doh",
    definitions: [{ meaning: "Money / cash", example: "Doh yangu imeisha, mwezi bado mrefu." }],
    partOfSpeech: "noun",
    origin: "From English slang 'dough' meaning money",
    tags: ["money"],
    relatedWords: ["ganji", "chapaa"],
  },
  {
    word: "packe",
    slug: "packe",
    definitions: [{ meaning: "Money", example: "Una packe? Tuende tucheze pool." }],
    partOfSpeech: "noun",
    tags: ["money"],
    relatedWords: ["ganji", "doh"],
  },
  {
    word: "hela",
    slug: "hela",
    definitions: [{ meaning: "Money / cash", example: "Hela zinaisha haraka siku hizi." }],
    partOfSpeech: "noun",
    origin: "Swahili/coastal word for money",
    tags: ["money"],
    relatedWords: ["ganji", "chapaa"],
  },
  {
    word: "omoka",
    slug: "omoka",
    definitions: [{ meaning: "To make it / to get rich / to succeed in life", example: "Tunafanya kazi hard ili tuomoke." }],
    partOfSpeech: "verb",
    tags: ["money", "success", "lifestyle"],
  },
  {
    word: "kuomoka",
    slug: "kuomoka",
    definitions: [{ meaning: "To come up / to get wealthy / to break through in life", example: "Atakuomoka hivi karibuni, anafanya kazi hard." }],
    partOfSpeech: "verb",
    tags: ["success", "money", "lifestyle"],
    relatedWords: ["omoka"],
  },
  {
    word: "m-sape",
    slug: "m-sape",
    definitions: [{ meaning: "M-PESA / mobile money transfer", example: "Nitakutumia pesa kwa m-sape, angalia simu." }],
    partOfSpeech: "noun",
    origin: "Coined by Sewersydaa in the song 'Cry Baby'",
    tags: ["money", "technology", "fintech"],
  },

  // ══════════════════════════════════════════════
  // PLACES & NEIGHBOURHOODS
  // ══════════════════════════════════════════════
  {
    word: "kanairo",
    slug: "kanairo",
    definitions: [{ meaning: "Nairobi city / the city / the capital", example: "Kanairo ni ngumu lakini maisha yako hapa." }],
    partOfSpeech: "noun",
    origin: "Popularised by Madocho in 2020, then spread via Trio Mio, Mejja",
    tags: ["places", "nairobi"],
    relatedWords: ["tao", "mji"],
  },
  {
    word: "balaluu",
    slug: "balaluu",
    definitions: [{ meaning: "Home / your place / where you rest", example: "Naenda balaluu, nimechoka sana." }],
    partOfSpeech: "noun",
    origin: "Introduced by Wakadinali in their 2022 song 'Balaluu'",
    tags: ["places", "home"],
    relatedWords: ["rotejo", "marima", "mta"],
  },
  {
    word: "rotejo",
    slug: "rotejo",
    definitions: [{ meaning: "Your house / your home / where you stay", example: "Rotejo yangu iko Zimmerman, karibu." }],
    partOfSpeech: "noun",
    tags: ["places", "home"],
    relatedWords: ["balaluu", "marima", "mta"],
  },
  {
    word: "mta",
    slug: "mta",
    definitions: [{ meaning: "Home / hood / your neighbourhood / estate", example: "Narudi mta, kumbe ndio kwangu." }],
    partOfSpeech: "noun",
    tags: ["places", "home", "neighbourhood"],
    relatedWords: ["rotejo", "balaluu"],
  },
  {
    word: "mayibe",
    slug: "mayibe",
    definitions: [{ meaning: "The yard / where you stay / your area", example: "Nitakuja mayibe yako usiku, nisubiria." }],
    partOfSpeech: "noun",
    tags: ["places", "home"],
    relatedWords: ["mta", "rotejo"],
  },
  {
    word: "zanabe",
    slug: "zanabe",
    definitions: [{ meaning: "Your hood / where you chill / your territory", example: "Zanabe yangu ni Umoja, kama ukuja ujue sheria." }],
    partOfSpeech: "noun",
    tags: ["places", "neighbourhood"],
  },
  {
    word: "choche",
    slug: "choche",
    definitions: [{ meaning: "A secret hideout / a hidden corner", example: "Wanakaa kwa choche, hakuna mtu anayejua." }],
    partOfSpeech: "noun",
    tags: ["places", "hiding"],
  },
  {
    word: "kortko",
    slug: "kortko",
    definitions: [{ meaning: "A court / basketball or football court", example: "Tutaenda kortko baada ya shule, game inakuwa." }],
    partOfSpeech: "noun",
    origin: "From English 'courtyard'",
    tags: ["places", "sports"],
  },
  {
    word: "oyole",
    slug: "oyole",
    definitions: [{ meaning: "Kayole estate / the Kayole neighbourhood", example: "Oyole ni heavy, watu wanajua kuishi maisha." }],
    partOfSpeech: "noun",
    origin: "Short for Kayole — Nairobi's Eastlands estate",
    tags: ["places", "nairobi", "eastlands"],
    region: "Nairobi",
  },
  {
    word: "muchatha",
    slug: "muchatha",
    definitions: [{ meaning: "Upcountry / the village / rural areas", example: "Nilienda muchatha sherehe ya Christmas." }],
    partOfSpeech: "noun",
    tags: ["places", "village", "upcountry"],
    relatedWords: ["ocha"],
  },
  {
    word: "ocha",
    slug: "ocha",
    definitions: [{ meaning: "Upcountry / village / rural home", example: "Narudi ocha Diwali, naona wazazi." }],
    partOfSpeech: "noun",
    tags: ["places", "village", "upcountry"],
    relatedWords: ["muchatha"],
  },
  {
    word: "stenje",
    slug: "stenje",
    definitions: [{ meaning: "A police station", example: "Alipelekwa stenje baada ya kushikwa." }],
    partOfSpeech: "noun",
    tags: ["places", "police"],
    relatedWords: ["ndondo"],
  },
  {
    word: "wathii",
    slug: "wathii",
    definitions: [{ meaning: "A market / especially a clothing market like Gikomba", example: "Ninaenda wathii kupata nguo za bei nzuri." }],
    partOfSpeech: "noun",
    origin: "From Kikuyu — a market or trading area",
    tags: ["places", "shopping", "market"],
    region: "Nairobi",
  },
  {
    word: "mboka",
    slug: "mboka",
    definitions: [{ meaning: "Work / job / hustle / your occupation", example: "Mboka yangu iko CBD, nafika mapema." }],
    partOfSpeech: "noun",
    tags: ["work", "hustle"],
    relatedWords: ["mraa"],
  },
  {
    word: "mraa",
    slug: "mraa",
    definitions: [{ meaning: "Your hustle / your work / sometimes the area you stay in", example: "Mraa wangu ni digital marketing, inakwenda." }],
    partOfSpeech: "noun",
    tags: ["work", "hustle", "places"],
    relatedWords: ["mboka"],
  },
  {
    word: "getto",
    slug: "getto",
    definitions: [{ meaning: "The ghetto / a low-income neighbourhood / the hood", example: "Ametoka getto, sasa ana penthouse." }],
    partOfSpeech: "noun",
    origin: "From English 'ghetto'",
    tags: ["places", "neighbourhood", "hood"],
  },

  // ══════════════════════════════════════════════
  // TRANSPORT
  // ══════════════════════════════════════════════
  {
    word: "mathree",
    slug: "mathree",
    definitions: [{ meaning: "A matatu / public minibus transport", example: "Mathree ya mbele imejaa, ngoja nyingine." }],
    partOfSpeech: "noun",
    origin: "From 'matatu' — the Kenyan public transport minibus",
    tags: ["transport", "matatu"],
    relatedWords: ["nganya", "ma3"],
  },
  {
    word: "ma3",
    slug: "ma3",
    definitions: [{ meaning: "A matatu / public transport minibus", example: "Ma3 imeniangusha kesho, sitafika kwa wakati." }],
    partOfSpeech: "noun",
    tags: ["transport", "matatu"],
    relatedWords: ["mathree", "nganya"],
  },
  {
    word: "nganya",
    slug: "nganya",
    definitions: [{ meaning: "A flashy / tricked-out matatu with screens, music, and lights", example: "Nganya ile ina sound system ya moto sana." }],
    partOfSpeech: "noun",
    tags: ["transport", "matatu", "culture"],
    relatedWords: ["mathree", "mboko"],
  },
  {
    word: "mboko",
    slug: "mboko",
    definitions: [{ meaning: "A flashy matatu / a tricked-out matatu", example: "Mboko ule ina neon lights hadi chini." }],
    partOfSpeech: "noun",
    tags: ["transport", "matatu"],
    relatedWords: ["nganya"],
  },
  {
    word: "mrenga",
    slug: "mrenga",
    definitions: [{ meaning: "A car / personal vehicle", example: "Kama si Benzo mrenga ni Bima — Wakadinali." }],
    partOfSpeech: "noun",
    origin: "Popularised by Wakadinali in their song 'Mrenga'",
    tags: ["transport", "cars"],
    relatedWords: ["pira"],
  },
  {
    word: "njikli",
    slug: "njikli",
    definitions: [{ meaning: "A bicycle / bike", example: "Alipanda njikli kutoka Eastlands mpaka town." }],
    partOfSpeech: "noun",
    tags: ["transport", "bicycle"],
  },
  {
    word: "spin",
    slug: "spin",
    definitions: [{ meaning: "To drive a car / to go for a drive", example: "Tuende spin tukizunguka Nairobi usiku." }],
    partOfSpeech: "verb",
    origin: "From English 'spin' meaning to drive around",
    tags: ["transport", "cars", "actions"],
  },
  {
    word: "manyanga",
    slug: "manyanga",
    definitions: [{ meaning: "Flashy cars / luxury vehicles / expensive rides", example: "Manyanga za Easich zina rims kubwa." }],
    partOfSpeech: "noun",
    origin: "From 'Manyanga za Easich' — reference to Eastlands flashy car culture",
    tags: ["transport", "cars", "lifestyle"],
  },

  // ══════════════════════════════════════════════
  // FASHION & APPEARANCE
  // ══════════════════════════════════════════════
  {
    word: "luku",
    slug: "luku",
    definitions: [{ meaning: "Style / fashion / dressed up well / your look", example: "Luku yake leo ni ngoma, amevaa vizuri sana." }],
    partOfSpeech: "noun",
    origin: "Popularised by Khaligraph Jones in his song 'Luku'",
    tags: ["fashion", "style"],
  },
  {
    word: "luku-kasuku",
    slug: "luku-kasuku",
    definitions: [{ meaning: "Old fashioned / outdated style / unfashionable", example: "Acha luku kasuku, vaa nguo za siku hizi." }],
    partOfSpeech: "expression",
    origin: "Popularised by Octopizzo commenting on Khaligraph Jones' fashion",
    tags: ["fashion", "style", "insult"],
  },
  {
    word: "shine",
    slug: "shine",
    definitions: [{ meaning: "To dress well / to outperform others / to glow up", example: "Leo nataka kushine, na event kubwa." }],
    partOfSpeech: "verb",
    tags: ["fashion", "success"],
  },
  {
    word: "tispo",
    slug: "tispo",
    definitions: [{ meaning: "Sports / sports shoes / sneakers", example: "Tispo zangu mpya ni za Nike, ni ngoma." }],
    partOfSpeech: "noun",
    origin: "Popularised by Mbogi Genje in 2020",
    tags: ["fashion", "sports", "shoes"],
  },
  {
    word: "ndula",
    slug: "ndula",
    definitions: [{ meaning: "Shoes / footwear", example: "Ndula zangu zimechakaa, ninahitaji mpya." }],
    partOfSpeech: "noun",
    tags: ["fashion", "shoes"],
    relatedWords: ["tispo"],
  },
  {
    word: "nyonginyo",
    slug: "nyonginyo",
    definitions: [{ meaning: "Socks", example: "Nyonginyo zangu zina holes, lazima nununue mpya." }],
    partOfSpeech: "noun",
    tags: ["fashion", "clothing"],
  },
  {
    word: "thogithi",
    slug: "thogithi",
    definitions: [{ meaning: "Socks / also used to mean condom", example: "Angalia, thogithi zake ni tofauti mbili." }],
    partOfSpeech: "noun",
    tags: ["fashion", "clothing"],
  },
  {
    word: "ngoma",
    slug: "ngoma",
    definitions: [{ meaning: "Music / a rubber shoe / something cool / a vibe", example: "Ngoma ya leo ni moto, DJ anacheza vizuri." }],
    partOfSpeech: "noun",
    origin: "Swahili for drum, repurposed to mean music or a good time",
    tags: ["music", "fashion", "everyday"],
  },
  {
    word: "njaro",
    slug: "njaro",
    definitions: [{ meaning: "A pose / style / a signature move", example: "Foto yake ina njaro nzuri, ana confidence." }],
    partOfSpeech: "noun",
    tags: ["fashion", "style", "social-media"],
  },
  {
    word: "wanjapi",
    slug: "wanjapi",
    definitions: [{ meaning: "A photo / photograph / picture", example: "Tuchukue wanjapi pamoja kwa party." }],
    partOfSpeech: "noun",
    tags: ["social-media", "everyday"],
  },
  {
    word: "akala",
    slug: "akala",
    definitions: [{ meaning: "Sandals made from old car tyres / traditional sandals", example: "Akala ni ngumu, zinaweza kaa miaka mingi." }],
    partOfSpeech: "noun",
    origin: "Footwear traditionally worn by Maasai and Kamba people",
    tags: ["fashion", "shoes", "culture"],
  },
  {
    word: "avunja",
    slug: "avunja",
    definitions: [{ meaning: "Boots / military or heavy factory boots", example: "Avunja zake ni za construction, solid." }],
    partOfSpeech: "noun",
    tags: ["fashion", "shoes"],
  },
  {
    word: "sahara",
    slug: "sahara",
    definitions: [{ meaning: "Safari boots / Bata Sahara brand boots", example: "Sahara ni viatu vya wote, ni durable." }],
    partOfSpeech: "noun",
    origin: "From the Bata Shoe Company Sahara brand",
    tags: ["fashion", "shoes"],
  },
  {
    word: "stud",
    slug: "stud",
    definitions: [{ meaning: "Football boots / studs / soccer cleats", example: "Stud zangu mpya zinafanya kasi kwa pitch." }],
    partOfSpeech: "noun",
    origin: "From English 'stud'",
    tags: ["sports", "fashion", "shoes"],
  },

  // ══════════════════════════════════════════════
  // FOOD & DRINK
  // ══════════════════════════════════════════════
  {
    word: "chipo",
    slug: "chipo",
    definitions: [{ meaning: "French fries / chips / fast food", example: "Nitashuka kwa chipo kwa dakika tano." }],
    partOfSpeech: "noun",
    origin: "From English 'chips'",
    tags: ["food", "fast-food"],
    relatedWords: ["jiva", "njiva"],
  },
  {
    word: "njoti",
    slug: "njoti",
    definitions: [{ meaning: "Groundnuts / peanuts", example: "Nilikula njoti njiani kurudi nyumbani." }],
    partOfSpeech: "noun",
    tags: ["food", "snacks"],
  },
  {
    word: "malo",
    slug: "malo",
    definitions: [{ meaning: "To eat / to finish something / also means 'up'", example: "Tumalo chakula haraka, tunachelewa." }],
    partOfSpeech: "verb",
    tags: ["food", "actions"],
    relatedWords: ["kumalo"],
  },
  {
    word: "kumalo",
    slug: "kumalo",
    definitions: [{ meaning: "To finish / to eat everything / to exhaust", example: "Kumalo chakula chote, kilikuwa kitamu." }],
    partOfSpeech: "verb",
    origin: "From Mbogi Nare's reggae crew; from Swahili 'kumaliza'",
    tags: ["food", "actions"],
    relatedWords: ["malo"],
  },
  {
    word: "manyake",
    slug: "manyake",
    definitions: [{ meaning: "Chunks of meat / also used to describe a plus-size woman", example: "Manyake ya nyama kwa sufuria inanuka vizuri." }],
    partOfSpeech: "noun",
    tags: ["food", "people"],
  },
  {
    word: "ketepa",
    slug: "ketepa",
    definitions: [{ meaning: "Tea / also khat (miraa) / or alcohol", example: "Nitakunywa ketepa moja asubuhi kabla sijaenda mboka." }],
    partOfSpeech: "noun",
    origin: "From Ketepa brand tea (Kenya Tea Packers)",
    tags: ["food", "drink"],
  },
  {
    word: "machupa",
    slug: "machupa",
    definitions: [{ meaning: "Glasses (eyewear) / also bottles of alcohol", example: "Machupa zake ni za designer, anapenda kuonekana." }],
    partOfSpeech: "noun",
    origin: "From Swahili 'chupa' meaning bottle",
    tags: ["fashion", "alcohol", "everyday"],
  },
  {
    word: "mzinga",
    slug: "mzinga",
    definitions: [{ meaning: "A full 1-litre bottle of alcohol", example: "Walileta mzinga ya Chrome na kuanza sherehe." }],
    partOfSpeech: "noun",
    origin: "From Swahili 'mzinga' meaning cannon/cylinder",
    tags: ["alcohol", "party"],
    relatedWords: ["chingri", "makali"],
  },
  {
    word: "chingri",
    slug: "chingri",
    definitions: [{ meaning: "Alcohol / alcoholic drink", example: "Watu wananywa chingri bila kushiba." }],
    partOfSpeech: "noun",
    tags: ["alcohol", "substances"],
    relatedWords: ["mzinga", "makali"],
  },
  {
    word: "makali",
    slug: "makali",
    definitions: [{ meaning: "Strong alcohol / spirits / gin or konyagi that needs a chaser", example: "Makali za konyagi zimemfanya asimame." }],
    partOfSpeech: "noun",
    tags: ["alcohol", "substances"],
    relatedWords: ["chingri", "mzinga"],
  },
  {
    word: "wamocho",
    slug: "wamocho",
    definitions: [{ meaning: "To drink alcohol / to take a drink", example: "Wanaenda wamocho baada ya kazi." }],
    partOfSpeech: "verb",
    tags: ["alcohol", "actions"],
  },
  {
    word: "ng-ango",
    slug: "ng-ango",
    definitions: [{ meaning: "An alcoholic / someone addicted to alcohol / a drunkard", example: "Ng'ang'o yule anakaa hapo pombe shop kila siku." }],
    partOfSpeech: "noun",
    tags: ["alcohol", "people", "negative"],
  },
  {
    word: "pewa",
    slug: "pewa",
    definitions: [{ meaning: "To be given a drink / to drink / to have a round", example: "Pewa moja, leo ni wangu." }],
    partOfSpeech: "verb",
    tags: ["alcohol", "actions"],
  },
  {
    word: "bleki",
    slug: "bleki",
    definitions: [{ meaning: "Blackout / drunk to the point of passing out / extremely tired", example: "Alikuwa bleki kabisa, tumemweka kiti." }],
    partOfSpeech: "adjective",
    origin: "From English 'blackout'",
    tags: ["alcohol", "states"],
  },
  {
    word: "ubao",
    slug: "ubao",
    definitions: [{ meaning: "Hungry / hunger", example: "Niko ubao, hakuna kitu kwa nyumba." }],
    partOfSpeech: "noun",
    tags: ["food", "states", "everyday"],
  },

  // ══════════════════════════════════════════════
  // SUBSTANCES
  // ══════════════════════════════════════════════
  {
    word: "mavela",
    slug: "mavela",
    definitions: [{ meaning: "Khat / miraa", example: "Wanamaliza mavela kila usiku." }],
    partOfSpeech: "noun",
    tags: ["substances", "khat"],
    relatedWords: ["jaba", "gwethe"],
  },
  {
    word: "kaveve-kazoze",
    slug: "kaveve-kazoze",
    definitions: [{ meaning: "Aggressively chewing khat / going hard on miraa", example: "Wanafanya kaveve kazoze hadi usiku." }],
    partOfSpeech: "expression",
    origin: "Went viral after Ngesh of Spider Clan used it; kaveve=khat, kazoze=getting aggressive",
    tags: ["substances", "khat", "expression"],
  },
  {
    word: "maini",
    slug: "maini",
    definitions: [{ meaning: "Fresh high-grade khat / premium miraa", example: "Maini mpya imefika, fresh kutoka Meru." }],
    partOfSpeech: "noun",
    tags: ["substances", "khat"],
    relatedWords: ["jaba", "gwethe"],
  },
  {
    word: "kindukulu",
    slug: "kindukulu",
    definitions: [{ meaning: "Marijuana / cannabis sativa", example: "Harufu ya kindukulu inatoka nje." }],
    partOfSpeech: "noun",
    tags: ["substances", "weed"],
    relatedWords: ["kolo", "ngusu"],
  },
  {
    word: "ngusu",
    slug: "ngusu",
    definitions: [{ meaning: "Marijuana / cannabis sativa", example: "Ngusu imefanya watu wawili wakose kazi." }],
    partOfSpeech: "noun",
    tags: ["substances", "weed"],
    relatedWords: ["kindukulu", "kolo"],
  },
  {
    word: "ngunga",
    slug: "ngunga",
    definitions: [{ meaning: "Cannabis sativa / marijuana", example: "Ngunga inanuka mbali." }],
    partOfSpeech: "noun",
    tags: ["substances", "weed"],
    relatedWords: ["kindukulu", "ngusu"],
  },
  {
    word: "ndom",
    slug: "ndom",
    definitions: [{ meaning: "Weed / marijuana", example: "Ndom ilitupeleka mahali mbali." }],
    partOfSpeech: "noun",
    tags: ["substances", "weed"],
    relatedWords: ["kindukulu"],
  },
  {
    word: "kolo",
    slug: "kolo",
    definitions: [{ meaning: "A roll of marijuana / a joint", example: "Walifanya kolo moja kisha wakalala." }],
    partOfSpeech: "noun",
    tags: ["substances", "weed"],
    relatedWords: ["shada", "nyongi"],
  },
  {
    word: "shada",
    slug: "shada",
    definitions: [{ meaning: "A roll of marijuana / a joint", example: "Shada moja inatosha usiku huu." }],
    partOfSpeech: "noun",
    tags: ["substances", "weed"],
    relatedWords: ["kolo", "nyongi"],
  },
  {
    word: "nyongi",
    slug: "nyongi",
    definitions: [{ meaning: "A small joint / a blunt so small it burns your fingers or lips", example: "Nyongi ile iliungua vidole." }],
    partOfSpeech: "noun",
    tags: ["substances", "weed"],
    relatedWords: ["kolo", "shada"],
  },
  {
    word: "kiombitho",
    slug: "kiombitho",
    definitions: [{ meaning: "Cannabis / marijuana", example: "Kiombitho kilitupeleka kwa safari ndefu." }],
    partOfSpeech: "noun",
    tags: ["substances", "weed"],
    relatedWords: ["kindukulu"],
  },
  {
    word: "ririma",
    slug: "ririma",
    definitions: [{ meaning: "Smoking / taking cannabis", example: "Wanaenda nje ya madarasa kwa ririma." }],
    partOfSpeech: "verb",
    tags: ["substances", "weed"],
  },
  {
    word: "vuva",
    slug: "vuva",
    definitions: [{ meaning: "To meditate / to take marijuana / to smoke weed", example: "Alikwenda peke yake kuvuva." }],
    partOfSpeech: "verb",
    tags: ["substances", "weed"],
  },
  {
    word: "kumedi",
    slug: "kumedi",
    definitions: [{ meaning: "To meditate / to be high after taking substances", example: "Anakumedi peke yake kwa chumba." }],
    partOfSpeech: "verb",
    tags: ["substances", "states"],
    relatedWords: ["vuva"],
  },
  {
    word: "shtimu",
    slug: "shtimu",
    definitions: [{ meaning: "High from weed / passionate / full of steam", example: "Msee alikuwa shtimu kwa game, hakubali kupoteza." }],
    partOfSpeech: "adjective",
    origin: "From English 'steam'",
    tags: ["substances", "states", "sports"],
  },
  {
    word: "ngwai",
    slug: "ngwai",
    definitions: [{ meaning: "Marijuana / weed", example: "Ngwai ya mtaani ni kali sana." }],
    partOfSpeech: "noun",
    tags: ["substances", "weed"],
    relatedWords: ["kindukulu", "ngusu"],
  },
  {
    word: "mbichwa",
    slug: "mbichwa",
    definitions: [{ meaning: "Something new / fresh / can also mean marijuana", example: "Mbichwa imefika kwa wathii, nguo mpya." }],
    partOfSpeech: "adjective",
    origin: "From Swahili 'mbichi' meaning raw/unripe/new",
    tags: ["everyday", "new", "substances"],
  },
  {
    word: "jaba",
    slug: "jaba",
    definitions: [{ meaning: "Khat / miraa / the stimulant chewed widely in Nairobi", example: "Jaba inaenda sana kwa Eastlands, market kubwa." }],
    partOfSpeech: "noun",
    tags: ["substances", "khat"],
    relatedWords: ["gwethe", "mavela", "ngwedhe"],
  },

  // ══════════════════════════════════════════════
  // MUSIC, DANCE & CULTURE
  // ══════════════════════════════════════════════
  {
    word: "shera",
    slug: "shera",
    definitions: [{ meaning: "To dance / to move / to vibe", example: "Muziki inabeba, watu wote wanashera." }],
    partOfSpeech: "verb",
    origin: "Derived from the Miondoko dance style",
    tags: ["dance", "music", "culture"],
  },
  {
    word: "chora-saba",
    slug: "chora-saba",
    definitions: [{ meaning: "To twerk / to bend over and dance suggestively", example: "Msichana alishera na kuchora saba kwa stage." }],
    partOfSpeech: "expression",
    tags: ["dance", "music"],
  },
  {
    word: "warena",
    slug: "warena",
    definitions: [{ meaning: "A flashy lifestyle / fire / something burning hot and exciting", example: "Warena ya Khaligraph ni ya moto sana." }],
    partOfSpeech: "noun",
    origin: "From Sheng word 'nare' meaning fire; popularised by Mbogi Genje and Khaligraph Jones",
    tags: ["lifestyle", "music", "culture"],
  },
  {
    word: "kiki",
    slug: "kiki",
    definitions: [{ meaning: "Clout / internet fame / social media influence", example: "Ana kiki mingi Instagram, followers nyingi." }],
    partOfSpeech: "noun",
    origin: "Borrowed from Tanzania where it is famous slang",
    tags: ["social-media", "culture", "fame"],
  },
  {
    word: "mboka-doba",
    slug: "mboka-doba",
    definitions: [{ meaning: "The music business / music hustle", example: "Mboka doba ni ngumu, lazima upigane." }],
    partOfSpeech: "expression",
    tags: ["music", "work", "hustle"],
  },
  {
    word: "rong-rende",
    slug: "rong-rende",
    definitions: [{ meaning: "The wrong crew / an outlaw group / Wakadinali's tagline", example: "Rong Rende ni lifestyle, si tu tag ya Wakadinali." }],
    partOfSpeech: "expression",
    origin: "Popularised by Wakadinali as their tagline",
    tags: ["music", "culture", "wakadinali"],
  },
  {
    word: "mziki",
    slug: "mziki",
    definitions: [{ meaning: "Music / a track / a song", example: "Mziki huu ni wa moto, imeingia chali." }],
    partOfSpeech: "noun",
    origin: "From Swahili 'muziki'",
    tags: ["music"],
    relatedWords: ["doba", "ngoma"],
  },
  {
    word: "nare",
    slug: "nare",
    definitions: [{ meaning: "Fire / something hot and exciting / flames", example: "Nare ya Wakadinali haisimami, ni ya moto." }],
    partOfSpeech: "noun",
    tags: ["expression", "fire", "music"],
    relatedWords: ["warena"],
  },
  {
    word: "mchongoano",
    slug: "mchongoano",
    definitions: [{ meaning: "Playful roasting / trading insults / witty banter / verbal battles", example: "Mchongoano wao ulifanya watu wacheke sana." }],
    partOfSpeech: "noun",
    origin: "From Swahili 'kuchangana' — mixing/rubbing against each other",
    tags: ["culture", "language", "fun"],
  },
  {
    word: "gotha-tena",
    slug: "gotha-tena",
    definitions: [{ meaning: "Pull it up again / replay it / do it again", example: "Gotha tena! Muziki huu ni ngoma." }],
    partOfSpeech: "expression",
    origin: "From Kikuyu; popularised by Breeder LW in 'Dedi Dedilee'",
    tags: ["music", "actions", "expression"],
  },

  // ══════════════════════════════════════════════
  // SCHOOL & EDUCATION
  // ══════════════════════════════════════════════
  {
    word: "mode",
    slug: "mode",
    definitions: [{ meaning: "A teacher / lecturer / instructor", example: "Mode wetu wa English ni mkali, homework kila siku." }],
    partOfSpeech: "noun",
    tags: ["education", "school", "people"],
    relatedWords: ["odijo"],
  },
  {
    word: "mbuku",
    slug: "mbuku",
    definitions: [{ meaning: "A book / textbook / novel", example: "Chukua mbuku yako, mode anakuja." }],
    partOfSpeech: "noun",
    tags: ["education", "school"],
  },
  {
    word: "kugwara",
    slug: "kugwara",
    definitions: [{ meaning: "To fail an exam / to flunk / to perform badly", example: "Aligwara maths, atakuwa na supplementary." }],
    partOfSpeech: "verb",
    tags: ["education", "school"],
  },
  {
    word: "tizi",
    slug: "tizi",
    definitions: [{ meaning: "Practice / training / rehearsal", example: "Tizi ya football iko saa kumi asubuhi." }],
    partOfSpeech: "noun",
    tags: ["education", "sports", "practice"],
  },
  {
    word: "box",
    slug: "box",
    definitions: [{ meaning: "University hostel / also to trap or seduce someone", example: "Naenda box yangu ku-relax baada ya class." }],
    partOfSpeech: "noun",
    tags: ["education", "places"],
  },

  // ══════════════════════════════════════════════
  // BODY & HEALTH
  // ══════════════════════════════════════════════
  {
    word: "ngasha",
    slug: "ngasha",
    definitions: [{ meaning: "To shower / to bathe / to wash up", example: "Niende ngasha kwanza kisha nitakuja." }],
    partOfSpeech: "verb",
    tags: ["body", "hygiene"],
  },
  {
    word: "thutha",
    slug: "thutha",
    definitions: [{ meaning: "Behind / at the back / buttocks", example: "Kaa thutha ukisubiria, atakuja." }],
    partOfSpeech: "noun",
    origin: "Direct translation from Kikuyu language",
    tags: ["body", "direction"],
    relatedWords: ["nyash", "aga"],
  },
  {
    word: "skele",
    slug: "skele",
    definitions: [{ meaning: "Very thin / skinny / a skeleton", example: "Msee amekuwa skele, hajali kula." }],
    partOfSpeech: "adjective",
    origin: "From English 'skeleton'",
    tags: ["body", "appearance"],
  },
  {
    word: "doshi",
    slug: "doshi",
    definitions: [{ meaning: "Manhood / male genitals / also a popular Nairobi metal company name", example: "Chuma ya doshi ni title ya song ya Eque iliyokuwa viral." }],
    partOfSpeech: "noun",
    origin: "Popularised by Eque's viral song 'Chuma ya Doshi'",
    tags: ["body", "slang"],
  },
  {
    word: "mjulubeng",
    slug: "mjulubeng",
    definitions: [{ meaning: "Male genitals / a man's private parts", example: "Mjulubeng ni serious matter, usicheze." }],
    partOfSpeech: "noun",
    tags: ["body", "adult"],
  },

  // ══════════════════════════════════════════════
  // ACTIONS & VERBS
  // ══════════════════════════════════════════════
  {
    word: "purura",
    slug: "purura",
    definitions: [{ meaning: "To play / to be a player / to flirt around", example: "Anapurura na wasichana wengi, ni purorist." }],
    partOfSpeech: "verb",
    tags: ["actions", "relationships"],
  },
  {
    word: "kudonjo",
    slug: "kudonjo",
    definitions: [{ meaning: "To come / to arrive / something interesting happening", example: "Kudonjo hapa, mambo ya burudani." }],
    partOfSpeech: "verb",
    tags: ["actions", "movement"],
    relatedWords: ["muok"],
  },
  {
    word: "muok",
    slug: "muok",
    definitions: [{ meaning: "Come / come over / arrive", example: "Muok hapa haraka, kuna habari." }],
    partOfSpeech: "verb",
    tags: ["actions", "movement"],
    relatedWords: ["kudonjo"],
  },
  {
    word: "kudade",
    slug: "kudade",
    definitions: [{ meaning: "To pour / to come (sexually) / context dependent", example: "Kudade remix ya Fancy Fingers ilikuwa hit ya 2022." }],
    partOfSpeech: "verb",
    origin: "Went viral after Fancy Fingers 'Kudade' remix",
    tags: ["actions", "adult"],
  },
  {
    word: "thigitha",
    slug: "thigitha",
    definitions: [{ meaning: "To cause trouble / to start problems / to stir drama", example: "Alikuja kwa party na akathigitha, sasa watu wamegombana." }],
    partOfSpeech: "verb",
    tags: ["actions", "trouble"],
    relatedWords: ["zoza"],
  },
  {
    word: "zoza",
    slug: "zoza",
    definitions: [{ meaning: "To cause trouble / to be aggressive / to start chaos", example: "Alikuwa akizoza kila mtu alikuja." }],
    partOfSpeech: "verb",
    tags: ["actions", "trouble"],
    relatedWords: ["thigitha"],
  },
  {
    word: "vayolens",
    slug: "vayolens",
    definitions: [{ meaning: "Violence / chaos / things are about to get wild", example: "Vayolens ilitokea baada ya match, polisi wakaja." }],
    partOfSpeech: "noun",
    origin: "From English 'violence'",
    tags: ["actions", "crime", "chaos"],
  },
  {
    word: "angukia",
    slug: "angukia",
    definitions: [{ meaning: "To stumble upon something good / to get lucky / to fall on", example: "Nilikuwa naangukia deal nzuri sana juzi." }],
    partOfSpeech: "verb",
    origin: "From Swahili 'kuanguka' meaning to fall",
    tags: ["actions", "luck"],
  },
  {
    word: "scan",
    slug: "scan",
    definitions: [{ meaning: "To be on the lookout / to watch your surroundings carefully", example: "Scan vizuri, karao wako jirani." }],
    partOfSpeech: "verb",
    tags: ["actions", "awareness", "street"],
  },
  {
    word: "chai",
    slug: "chai",
    definitions: [{ meaning: "To steal / to take something that isn't yours", example: "Alimchai simu kwa giza, mtiaji." }],
    partOfSpeech: "verb",
    origin: "Swahili for tea, repurposed to mean 'take a sip of someone's things'",
    tags: ["actions", "crime"],
    relatedWords: ["peremba", "lambwa"],
  },
  {
    word: "lambwa",
    slug: "lambwa",
    definitions: [{ meaning: "To be robbed / to get stolen from", example: "Alilambwa na bag yake kwa CBD." }],
    partOfSpeech: "verb",
    tags: ["actions", "crime"],
    relatedWords: ["chai", "peremba"],
  },
  {
    word: "setiwa",
    slug: "setiwa",
    definitions: [{ meaning: "To be beaten up / to be set up / to be ambushed", example: "Alisetiwa na magondi kwa njia ya nyumbani." }],
    partOfSpeech: "verb",
    tags: ["actions", "violence", "crime"],
  },
  {
    word: "mendea",
    slug: "mendea",
    definitions: [{ meaning: "To encroach on someone / to take their partner or belongings", example: "Akamendea manzi wa morio wake, mambo yakawa ngumu." }],
    partOfSpeech: "verb",
    tags: ["actions", "relationships", "negative"],
  },
  {
    word: "nyandua",
    slug: "nyandua",
    definitions: [{ meaning: "To get intimate / to have sex", example: "Hawakutoka nje, wananyandua kwa nyumba." }],
    partOfSpeech: "verb",
    tags: ["actions", "adult", "relationships"],
  },
  {
    word: "kumanga",
    slug: "kumanga",
    definitions: [{ meaning: "To have sex / to eat (food) — context dependent", example: "Alikula — kumaliza chakula chote." }],
    partOfSpeech: "verb",
    tags: ["actions", "adult", "food"],
  },
  {
    word: "banja",
    slug: "banja",
    definitions: [{ meaning: "To talk / to speak / to have a conversation", example: "Wabanje kidogo, mwe na undamano." }],
    partOfSpeech: "verb",
    tags: ["actions", "communication"],
    relatedWords: ["saloka", "barojaa"],
  },
  {
    word: "cheza-chini",
    slug: "cheza-chini",
    definitions: [{ meaning: "To play it cool / to stay calm / to lay low", example: "Cheza chini, hali bado inaendelea." }],
    partOfSpeech: "expression",
    tags: ["actions", "advice", "expression"],
  },
  {
    word: "jipin",
    slug: "jipin",
    definitions: [{ meaning: "To have protection / to be secured / to be covered", example: "Jipin kabla ya kwenda, street ni ngumu." }],
    partOfSpeech: "verb",
    tags: ["actions", "safety"],
  },
  {
    word: "dandia",
    slug: "dandia",
    definitions: [{ meaning: "To step on something / to tread on / go / step on it", example: "Dandia gari, tunachelewa sana." }],
    partOfSpeech: "verb",
    tags: ["actions", "movement"],
  },
  {
    word: "kuchomeka",
    slug: "kuchomeka",
    definitions: [{ meaning: "To get burnt / to get caught / to make a mistake", example: "Umechomeka sana leo, hukufaa kusema hivyo." }],
    partOfSpeech: "verb",
    tags: ["everyday", "mistakes"],
  },

  // ══════════════════════════════════════════════
  // STATES & FEELINGS
  // ══════════════════════════════════════════════
  {
    word: "gwaya",
    slug: "gwaya",
    definitions: [{ meaning: "To fear / to be scared / to be intimidated", example: "Aligwaya anapowaona magondi." }],
    partOfSpeech: "verb",
    tags: ["emotions", "fear"],
    relatedWords: ["njeve"],
  },
  {
    word: "imbo",
    slug: "imbo",
    definitions: [{ meaning: "Fake / not original / a counterfeit", example: "Hii watch ni imbo, si Rolex ya kweli." }],
    partOfSpeech: "adjective",
    tags: ["everyday", "negative"],
  },
  {
    word: "sare",
    slug: "sare",
    definitions: [{ meaning: "Good / fine / of good quality", example: "Kazi yake ni sare, hakuna neno." }],
    partOfSpeech: "adjective",
    tags: ["everyday", "compliment"],
    relatedWords: ["poa", "shavaa"],
  },
  {
    word: "borre",
    slug: "borre",
    definitions: [{ meaning: "Boring / useless / a waste of time", example: "Party ile ilikuwa borre, watu hawakuonekana." }],
    partOfSpeech: "adjective",
    origin: "From English 'boring'",
    tags: ["emotions", "negative"],
  },
  {
    word: "kajanja",
    slug: "kajanja",
    definitions: [{ meaning: "Smart / clever / intelligent", example: "Msee ni kajanja sana, atasort hii situation." }],
    partOfSpeech: "adjective",
    tags: ["personality", "compliment"],
    relatedWords: ["mjanja"],
  },
  {
    word: "mjanja",
    slug: "mjanja",
    definitions: [{ meaning: "Smart / cunning / clever / streetwise", example: "Mjanja wa street anajua kila kitu." }],
    partOfSpeech: "adjective",
    origin: "Swahili for cunning/clever",
    tags: ["personality", "compliment"],
    relatedWords: ["kajanja"],
  },
  {
    word: "chizi",
    slug: "chizi",
    definitions: [{ meaning: "Crazy / mad / also used to say something is hot or exciting", example: "Msee ni chizi kabisa, alifanya vitu vya ajabu." }],
    partOfSpeech: "adjective",
    origin: "From English 'crazy' / Swahili 'kichaa'",
    tags: ["personality", "everyday"],
  },
  {
    word: "moto",
    slug: "moto",
    definitions: [{ meaning: "Fire / hot / something exciting / trending right now", example: "Track yake mpya ni moto, watu wote wanaimba." }],
    partOfSpeech: "adjective",
    origin: "Swahili for 'hot/fire'",
    tags: ["everyday", "compliment", "music"],
  },

  // ══════════════════════════════════════════════
  // MISC OBJECTS & ITEMS
  // ══════════════════════════════════════════════
  {
    word: "burungo",
    slug: "burungo",
    definitions: [{ meaning: "Merchandise / goods / bootleg items / cargo", example: "Burungo imetoka China, bei ni chini." }],
    partOfSpeech: "noun",
    tags: ["shopping", "business", "everyday"],
  },
  {
    word: "mbosho",
    slug: "mbosho",
    definitions: [{ meaning: "A wallet / purse / bag", example: "Mbosho yangu imeanguka, nilikimbia nikusort." }],
    partOfSpeech: "noun",
    tags: ["everyday", "accessories"],
  },
  {
    word: "blada",
    slug: "blada",
    definitions: [{ meaning: "A strip of bicycle or car tyre tubing used to make games or catapults", example: "Watoto wanacheza blada kwa uwanja." }],
    partOfSpeech: "noun",
    tags: ["everyday", "games", "childhood"],
  },
  {
    word: "stoko",
    slug: "stoko",
    definitions: [{ meaning: "Stock / supply / having enough", example: "Stoko ya unga imeisha, lazima unune." }],
    partOfSpeech: "noun",
    origin: "From English 'stock'",
    tags: ["business", "everyday"],
  },
  {
    word: "juala",
    slug: "juala",
    definitions: [{ meaning: "A condom / also a plastic carrier bag", example: "Juala ni muhimu, usalama kwanza." }],
    partOfSpeech: "noun",
    tags: ["health", "everyday"],
  },
  {
    word: "ngono",
    slug: "ngono",
    definitions: [{ meaning: "A cart / mkokoteni / pushcart", example: "Wanaendesha ngono kwa market wanasort mali." }],
    partOfSpeech: "noun",
    tags: ["transport", "work", "market"],
  },
  {
    word: "mshwari",
    slug: "mshwari",
    definitions: [{ meaning: "Calm / chill / no stress / also refers to Mshwari mobile loan product", example: "Mshwari tu, mambo yatashughulikiwa." }],
    partOfSpeech: "adjective",
    tags: ["expression", "calm", "fintech"],
  },
  {
    word: "thiang",
    slug: "thiang",
    definitions: [{ meaning: "A high-end smartphone / a new fancy phone", example: "Amenunua thiang mpya, iPhone 15 Pro." }],
    partOfSpeech: "noun",
    tags: ["technology", "phones"],
    relatedWords: ["mokia", "tonje"],
  },
  {
    word: "tonje",
    slug: "tonje",
    definitions: [{ meaning: "A mobile phone", example: "Tonje yake imekufa, battery imeisha." }],
    partOfSpeech: "noun",
    tags: ["technology", "phones"],
    relatedWords: ["mokia", "thiang"],
  },
  {
    word: "mulika-mwizi",
    slug: "mulika-mwizi",
    definitions: [{ meaning: "An old basic phone / a feature phone / not a smartphone", example: "Bado ana mulika mwizi, hajasasisha." }],
    partOfSpeech: "noun",
    origin: "Literally 'illuminate the thief' — old phones used as torches",
    tags: ["technology", "phones"],
    relatedWords: ["thiang", "tonje"],
  },
  {
    word: "mbulu",
    slug: "mbulu",
    definitions: [{ meaning: "Television / TV / also a person who has gone mad", example: "Angalia mbulu, news inasema nini?" }],
    partOfSpeech: "noun",
    tags: ["technology", "everyday"],
  },
  {
    word: "tebo",
    slug: "tebo",
    definitions: [{ meaning: "Table / table tennis", example: "Wanacheza tebo kwa club, moto sana." }],
    partOfSpeech: "noun",
    origin: "From English 'table'",
    tags: ["sports", "everyday"],
  },
  {
    word: "mbachu",
    slug: "mbachu",
    definitions: [{ meaning: "A room / a house / also khat", example: "Mbachu yake ni ndogo lakini iko sawa." }],
    partOfSpeech: "noun",
    tags: ["places", "home", "substances"],
  },

  // ══════════════════════════════════════════════
  // SOCIAL MEDIA & GEN Z
  // ══════════════════════════════════════════════
  {
    word: "danguch",
    slug: "danguch",
    definitions: [{ meaning: "An outgoing person / a social extrovert / especially an outgoing lady", example: "Huyu dem ni danguch, anaenda kila party." }],
    partOfSpeech: "noun",
    origin: "Popularised by Andrew Kibe in his livestreams",
    tags: ["personality", "social-media", "genz"],
  },
  {
    word: "slay-queen",
    slug: "slay-queen",
    definitions: [{ meaning: "A fashionable woman who always looks her best / someone living beyond their means for appearances", example: "Slay queen wa Instagram yake si wealth ya kweli." }],
    partOfSpeech: "noun",
    tags: ["people", "social-media", "culture"],
  },
  {
    word: "mzungu",
    slug: "mzungu",
    definitions: [{ meaning: "A white person / foreigner / someone who wanders around aimlessly", example: "Mzungu alikuwa anauliza maswali mengi kwa matatu." }],
    partOfSpeech: "noun",
    origin: "Literally 'someone who wanders aimlessly'",
    tags: ["people", "culture", "tourism"],
  },
  {
    word: "kimbokta",
    slug: "kimbokta",
    definitions: [{ meaning: "A long time ago / back in the day / ages ago", example: "Hiyo ilikuwa kimbokta, usijali." }],
    partOfSpeech: "adverb",
    tags: ["time", "expression"],
  },
  {
    word: "ndirau",
    slug: "ndirau",
    definitions: [{ meaning: "Strolling / going for a walk / a leisurely round", example: "Niende ndirau kidogo, nifeel hewa safi." }],
    partOfSpeech: "noun",
    origin: "From 'raundi' with Sheng syllable switch",
    tags: ["actions", "lifestyle"],
  },
  {
    word: "pupa",
    slug: "pupa",
    definitions: [{ meaning: "A young beautiful girl / a pupa (someone fresh/new)", example: "Pupa za campus ni nyingi, wako form." }],
    partOfpronoun: "noun",
    tags: ["people", "girls", "youth"],
  },

  // ══════════════════════════════════════════════
  // POLICE & CRIME
  // ══════════════════════════════════════════════
  {
    word: "hessy",
    slug: "hessy",
    definitions: [{ meaning: "A police officer", example: "Hessy wamekaa corner, wacha upole." }],
    partOfSpeech: "noun",
    tags: ["police", "authority"],
    relatedWords: ["karao", "mavedi", "sinya"],
  },
  {
    word: "ponyi",
    slug: "ponyi",
    definitions: [{ meaning: "Police / a police officer", example: "Ponyi wameweka checkpoint, twende njia nyingine." }],
    partOfSpeech: "noun",
    tags: ["police", "authority"],
    relatedWords: ["karao", "mavedi"],
  },
  {
    word: "mbaru",
    slug: "mbaru",
    definitions: [{ meaning: "Police officers", example: "Mbaru wamekimbia nyuma yake, mwende." }],
    partOfSpeech: "noun",
    tags: ["police", "authority"],
    relatedWords: ["karao", "mavedi"],
  },
  {
    word: "pinji",
    slug: "pinji",
    definitions: [{ meaning: "A thief / pickpocket / phone snatcher", example: "Pinji wa CBD ni hatari, shika mfuko wako." }],
    partOfSpeech: "noun",
    tags: ["crime", "people"],
    relatedWords: ["regre", "dingo"],
  },
  {
    word: "saigon",
    slug: "saigon",
    definitions: [{ meaning: "A police officer", example: "Saigon amekusimamisha, toa karatasi zako." }],
    partOfSpeech: "noun",
    tags: ["police", "authority"],
    relatedWords: ["karao", "mavedi"],
  },

  // ══════════════════════════════════════════════
  // SPECIAL PHRASES
  // ══════════════════════════════════════════════
  {
    word: "ndovu-ni-kuu",
    slug: "ndovu-ni-kuu",
    definitions: [{ meaning: "The elephant is big / used to say something or someone is huge and unstoppable", example: "Ndovu ni kuu — Khaligraph ni king wa Kenya rap." }],
    partOfSpeech: "expression",
    origin: "Popularised by Krispah's song featuring Khaligraph Jones and Boutross",
    tags: ["expression", "music", "culture"],
  },
  {
    word: "mbare",
    slug: "mbare",
    definitions: [{ meaning: "A slap / also a party or a hangout session", example: "Mbare ilikuwa kali sana, tulifurahia usiku." }],
    partOfSpeech: "noun",
    tags: ["actions", "party", "violence"],
  },
  {
    word: "chobo",
    slug: "chobo",
    definitions: [{ meaning: "A nutmeg in football / getting the ball between an opponent's legs", example: "Alimfanyia chobo na akampita vizuri." }],
    partOfSpeech: "noun",
    tags: ["sports", "football"],
  },
  {
    word: "kanambo",
    slug: "kanambo",
    definitions: [{ meaning: "Vybz Kartel / a reference to the Jamaican dancehall artist", example: "Anasikiliza kanambo, ni fan wa dancehall." }],
    partOfSpeech: "noun",
    origin: "Kenyan slang reference to Addidjah Palmer aka Vybz Kartel",
    tags: ["music", "culture", "dancehall"],
  },
  {
    word: "kc",
    slug: "kc",
    definitions: [{ meaning: "Kenya Cane (local spirit) / Karen Cowboy bar", example: "Tulinywa KC usiku, bei nzuri." }],
    partOfSpeech: "noun",
    tags: ["alcohol", "nairobi"],
  },
  {
    word: "riba",
    slug: "riba",
    definitions: [{ meaning: "A story / gossip / what happened / news", example: "Nishow riba, nini kilitokea jana usiku?" }],
    partOfSpeech: "noun",
    tags: ["communication", "gossip"],
    relatedWords: ["sereche", "radar"],
  },
  {
    word: "smarter",
    slug: "smarter",
    definitions: [{ meaning: "A genius / a pickpocket / a thief / a rich clean person", example: "Smarter wa class yetu anajua kila kitu." }],
    partOfSpeech: "noun",
    tags: ["people", "personality", "crime"],
  },
  {
    word: "lamba-lolo",
    slug: "lamba-lolo",
    definitions: [{ meaning: "Licking a lollipop / sweet talk / flattering someone", example: "Anafanya lamba lolo tu, anataka kitu." }],
    partOfSpeech: "expression",
    tags: ["expression", "relationships"],
  },
  {
    word: "kanairo",
    slug: "kanairo-alt",
    definitions: [{ meaning: "Nairobi — the city of hustle", example: "Kanairo haitaki watu wazito, uwe na nguvu." }],
    partOfSpeech: "noun",
    tags: ["places", "nairobi"],
  },
  {
    word: "wan-tu",
    slug: "wan-tu",
    definitions: [{ meaning: "To go on foot / to walk / also to hit rapidly in a fight", example: "Wan tu yake ilikuwa mbaya, msee akaanguka." }],
    partOfSpeech: "verb",
    origin: "From English 'one two' — hitting rapidly",
    tags: ["transport", "actions", "violence"],
  },
  {
    word: "bossy",
    slug: "bossy",
    definitions: [{ meaning: "A respected person / a peer / a friend / someone you look up to", example: "Bossy wangu alinisort kwa wakati mgumu." }],
    partOfSpeech: "noun",
    tags: ["people", "respect", "friends"],
    region: "Nairobi",
  },
  {
    word: "hesabu",
    slug: "hesabu",
    definitions: [{ meaning: "Math / calculations / counting the cost / thinking through consequences", example: "Fanya hesabu kwanza kabla ya kutumia pesa." }],
    partOfSpeech: "noun",
    origin: "Swahili for arithmetic",
    tags: ["education", "money", "everyday"],
  },
  {
    word: "peng",
    slug: "peng",
    definitions: [{ meaning: "A beautiful / attractive girl / pengting", example: "Yule dem ni peng, utamkosa eyes." }],
    partOfSpeech: "noun",
    origin: "From British slang 'peng' meaning attractive",
    tags: ["people", "girls", "compliment"],
    relatedWords: ["supu", "msupa"],
  },
  {
    word: "kucheza-roho",
    slug: "kucheza-roho",
    definitions: [{ meaning: "To be reckless / to take risks / to mess around with serious matters", example: "Usikucheze roho na hii, mambo ni ya kweli." }],
    partOfSpeech: "expression",
    tags: ["expression", "warning", "reckless"],
  },
  {
    word: "msoto",
    slug: "msoto-v2",
    definitions: [{ meaning: "Poverty / being broke / financial hardship", example: "Msoto unanisumbua sana wiki hii." }],
    partOfSpeech: "noun",
    tags: ["money", "poverty"],
  },
  {
    word: "mchoro",
    slug: "mchoro",
    definitions: [{ meaning: "A plan / a scheme / a way to get something done", example: "Ana mchoro wa kupata pesa haraka." }],
    partOfSpeech: "noun",
    tags: ["plans", "hustle", "street"],
  },
  {
    word: "kujaribu",
    slug: "kujaribu",
    definitions: [{ meaning: "To try / to attempt / to test something", example: "Kujaribu hakudhuru, jaribu tu." }],
    partOfSpeech: "verb",
    tags: ["actions", "motivation"],
  },
  {
    word: "mshanga",
    slug: "mshanga",
    definitions: [{ meaning: "Surprise / something unexpected / to be amazed", example: "Mshanga wake ilikuwa kubwa alipopata promotion." }],
    partOfSpeech: "noun",
    tags: ["emotions", "expression"],
  },
  {
    word: "kutesa",
    slug: "kutesa",
    definitions: [{ meaning: "To suffer / to struggle / to go through hard times", example: "Wanakutesa mtaani, waambie watoke." }],
    partOfSpeech: "verb",
    tags: ["emotions", "street", "struggle"],
  },
  {
    word: "slay",
    slug: "slay",
    definitions: [{ meaning: "To look great / to perform exceptionally / to kill it", example: "Alislay kwa show, watu wakapiga makofi." }],
    partOfSpeech: "verb",
    origin: "From English/American slang 'slay'",
    tags: ["fashion", "success", "genz"],
  },
  {
    word: "chapchap",
    slug: "chapchap",
    definitions: [{ meaning: "Quickly / fast / in a hurry / right away", example: "Fanya chapchap, tunaenda." }],
    partOfSpeech: "adverb",
    tags: ["everyday", "speed"],
    relatedWords: ["teke", "mbioni"],
  },
  {
    word: "kunyonga",
    slug: "kunyonga",
    definitions: [{ meaning: "To struggle / to persevere / to push through difficulties", example: "Tunanyonga hapa kwa mwisho wa mwezi." }],
    partOfSpeech: "verb",
    tags: ["struggle", "hustle", "motivation"],
  },
  {
    word: "pongezi",
    slug: "pongezi",
    definitions: [{ meaning: "Congratulations / well done / props", example: "Pongezi kwa promotion yako, umefanya vizuri." }],
    partOfSpeech: "expression",
    origin: "From Swahili 'pongezi' meaning congratulations",
    tags: ["expression", "celebration"],
  },
  {
    word: "msema-kweli",
    slug: "msema-kweli",
    definitions: [{ meaning: "Someone who speaks the truth / a straight talker / no cap", example: "Msema kweli ana maadui — lakini amesema ukweli." }],
    partOfSpeech: "noun",
    origin: "Swahili expression meaning 'truth-teller'",
    tags: ["personality", "expression", "honesty"],
  },
  {
    word: "kuingia-field",
    slug: "kuingia-field",
    definitions: [{ meaning: "To enter the dating scene / to start pursuing girls / to get into the game", example: "Alitoka relationship na sasa ameanza kuingia field." }],
    partOfSpeech: "expression",
    tags: ["relationships", "dating", "expression"],
  },
  {
    word: "shughuli",
    slug: "shughuli",
    definitions: [{ meaning: "Business / affairs / something to attend to / work", example: "Ana shughuli kubwa leo, hataweza kuja." }],
    partOfSpeech: "noun",
    origin: "Swahili for 'business/affairs'",
    tags: ["work", "everyday"],
  },
  {
    word: "kuchomeka",
    slug: "kuchomeka-v2",
    definitions: [{ meaning: "To get exposed / to get caught red-handed", example: "Alichomeka anapojaribu kuiba mitihani." }],
    partOfSpeech: "verb",
    tags: ["crime", "mistakes"],
  },
];

// ── Runner ─────────────────────────────────────────────────────
async function seed() {
  const uri = process.env.MONGODB_URI;
  if (!uri) {
    console.error("❌  MONGODB_URI not found in .env.local");
    process.exit(1);
  }

  // Deduplicate words array by slug before inserting
  const seen = new Set<string>();
  const dedupedWords = words.filter((w) => {
    if (seen.has(w.slug)) return false;
    seen.add(w.slug);
    return true;
  });

  console.log("🔌  Connecting to MongoDB...");
  await mongoose.connect(uri);
  console.log("✅  Connected!\n");

  console.log(`🌱  Seeding ${dedupedWords.length} words...`);
  let added = 0;
  let skipped = 0;

  for (const word of dedupedWords) {
    try {
      const result = await Word.findOneAndUpdate(
        { slug: word.slug },
        { $setOnInsert: word },
        { upsert: true, returnDocument: "before" }
      );
      if (result === null) {
        added++;
        console.log(`   ✔  ${word.word}`);
      } else {
        skipped++;
        console.log(`   ⏭  Skipped (exists): ${word.word}`);
      }
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } catch (err: any) {
      console.warn(`   ⚠  Error on "${word.word}": ${err.message}`);
      skipped++;
    }
  }

  console.log(`\n🎉  Done! ${added} new words added, ${skipped} already existed.`);
  await mongoose.disconnect();
  process.exit(0);
}

seed().catch((err) => {
  console.error("💥  Seed failed:", err);
  process.exit(1);
});