// =============================================================
// Sheng Dictionary — MongoDB Seed File
// =============================================================
// HOW TO RUN:
//   1. Make sure MONGODB_URI is set in your .env.local
//   2. Run: npx tsx scripts/seed.ts
//      (or: pnpm dlx tsx scripts/seed.ts)
// =============================================================

import mongoose from "mongoose";
import dotenv from "dotenv";
import path from "path";

dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

// ── Schema (inline so script is self-contained) ──────────────
const definitionSchema = new mongoose.Schema({
    meaning: String,
    example: String,
    addedBy: { type: String, default: "seed" },
});

const wordSchema = new mongoose.Schema(
    {
        word: { type: String, required: true, unique: true, lowercase: true, trim: true },
        slug: { type: String, required: true, unique: true, lowercase: true, trim: true },
        definitions: [definitionSchema],
        partOfSpeech: {
            type: String,
            enum: ["noun", "verb", "adjective", "expression", "adverb"],
            default: "noun",
        },
        origin: String,
        relatedWords: [String],
        region: { type: String, default: "Nationwide" },
        status: { type: String, enum: ["pending", "approved", "rejected"], default: "approved" },
        viewCount: { type: Number, default: 0 },
        isFeatured: { type: Boolean, default: true },
        tags: [String],
        submittedBy: { type: String, default: "seed" },
    },
    { timestamps: true }
);

const Word = mongoose.models.Word || mongoose.model("Word", wordSchema);

// ── Seed Data ─────────────────────────────────────────────────
const words = [
    // ── GREETINGS & CONVERSATION ──────────────────────────────
    {
        word: "sasa",
        slug: "sasa",
        definitions: [{ meaning: "What's up? / How are you?", example: "Sasa buda, mambo?" }],
        partOfSpeech: "expression",
        origin: "Swahili — 'now', repurposed as a greeting",
        tags: ["greetings", "everyday"],
        region: "Nationwide",
    },
    {
        word: "niaje",
        slug: "niaje",
        definitions: [{ meaning: "How are you? / What's up?", example: "Niaje msee, uko form?" }],
        partOfSpeech: "expression",
        origin: "Swahili corruption of 'ni aje' (how is it)",
        tags: ["greetings", "everyday"],
        region: "Nationwide",
    },
    {
        word: "poa",
        slug: "poa",
        definitions: [{ meaning: "Cool / Good / Fine", example: "Mambo? Poa kabisa!" }],
        partOfSpeech: "adjective",
        origin: "Swahili 'poa' meaning cool/calm",
        tags: ["everyday", "response"],
        region: "Nationwide",
    },
    {
        word: "rada",
        slug: "rada",
        definitions: [{ meaning: "What's up? / What's going on? / What's popping?", example: "Rada wewe, umekuwa busy sana." }],
        partOfSpeech: "expression",
        tags: ["greetings", "genz"],
        region: "Nationwide",
    },
    {
        word: "form",
        slug: "form",
        definitions: [{ meaning: "A plan or what's happening. Used to ask about or describe a situation.", example: "Una form gani usiku?" }],
        partOfSpeech: "noun",
        tags: ["everyday", "plans"],
        region: "Nationwide",
    },
    {
        word: "manze",
        slug: "manze",
        definitions: [{ meaning: "An expression used to start or continue a conversation, or to express surprise", example: "Manze ulikuwa wapi? Nimekuwa naki-stress!" }],
        partOfSpeech: "expression",
        tags: ["everyday", "expression"],
        region: "Nationwide",
    },
    {
        word: "riang",
        slug: "riang",
        definitions: [{ meaning: "What's up / How are things?", example: "Riang buda, habari zako?" }],
        partOfSpeech: "expression",
        tags: ["greetings"],
        region: "Nairobi",
    },
    {
        word: "cuzo",
        slug: "cuzo",
        definitions: [{ meaning: "A phrase used to start a friendly conversation with someone, similar to 'cousin' or 'bro'", example: "Cuzo, unanielewa?" }],
        partOfSpeech: "expression",
        tags: ["greetings", "genz"],
        region: "Nationwide",
    },

    // ── PEOPLE ────────────────────────────────────────────────
    {
        word: "msee",
        slug: "msee",
        definitions: [{ meaning: "A guy / dude / man. Used to refer to any male person.", example: "Yule msee anajua kushoot." }],
        partOfSpeech: "noun",
        origin: "Corruption of Swahili 'mzee' (elder/old man)",
        tags: ["people", "everyday"],
        region: "Nationwide",
    },
    {
        word: "dem",
        slug: "dem",
        definitions: [{ meaning: "A girl / young woman", example: "Yule dem ni mrembo sana." }],
        partOfSpeech: "noun",
        origin: "From English 'dame'",
        tags: ["people", "girls"],
        region: "Nationwide",
    },
    {
        word: "manzi",
        slug: "manzi",
        definitions: [{ meaning: "A girl / girlfriend", example: "Manzi wake ni mzuri sana." }],
        partOfSpeech: "noun",
        tags: ["people", "girls", "relationships"],
        region: "Nationwide",
    },
    {
        word: "buda",
        slug: "buda",
        definitions: [{ meaning: "Father / older male person / term of address for a male friend", example: "Buda wangu alinisaidia pesa." }],
        partOfSpeech: "noun",
        origin: "Corruption of 'baba' (father)",
        tags: ["people", "family", "everyday"],
        region: "Nationwide",
    },
    {
        word: "mathe",
        slug: "mathe",
        definitions: [{ meaning: "Mother / mom", example: "Mathe anakuita, nenda haraka." }],
        partOfSpeech: "noun",
        origin: "Corruption of English 'mother'",
        tags: ["people", "family"],
        region: "Nationwide",
    },
    {
        word: "mbogi",
        slug: "mbogi",
        definitions: [{ meaning: "A crew / group of friends or associates", example: "Mbogi yangu tunakaa Eastlands." }],
        partOfSpeech: "noun",
        tags: ["people", "social", "crew"],
        region: "Nationwide",
    },
    {
        word: "morio",
        slug: "morio",
        definitions: [{ meaning: "A male friend", example: "Morio wangu alikuja jana." }],
        partOfSpeech: "noun",
        tags: ["people", "friends"],
        region: "Nairobi",
    },
    {
        word: "bazu",
        slug: "bazu",
        definitions: [{ meaning: "A respected person / someone considered a big man or leader", example: "Yule bazu ndiye anamiliki area." }],
        partOfSpeech: "noun",
        tags: ["people", "respect", "status"],
        region: "Nationwide",
    },
    {
        word: "donga",
        slug: "donga",
        definitions: [{ meaning: "Your boss / a CEO / a person in charge", example: "Nitaongea na donga wa hii kazi." }],
        partOfSpeech: "noun",
        tags: ["people", "work", "status"],
        region: "Nationwide",
    },
    {
        word: "bazenga",
        slug: "bazenga",
        definitions: [{ meaning: "Someone who people like and respect", example: "Yeye ni bazenga wa area hii." }],
        partOfSpeech: "noun",
        tags: ["people", "respect"],
        region: "Nairobi",
    },
    {
        word: "sonko",
        slug: "sonko",
        definitions: [{ meaning: "A rich person / boss / someone with money", example: "Yule mse ni Sonko, ana ma-V8 mbili." }],
        partOfSpeech: "noun",
        tags: ["people", "money", "status"],
        region: "Nationwide",
    },
    {
        word: "riambez",
        slug: "riambez",
        definitions: [{ meaning: "A cute girl", example: "Ile riambez ulikuwa naye jana ni mzuri." }],
        partOfSpeech: "noun",
        tags: ["people", "girls", "compliment"],
        region: "Nairobi",
    },
    {
        word: "mpoa",
        slug: "mpoa",
        definitions: [{ meaning: "A cute or awesome person / something great", example: "Yeye ni mpoa, anavaa vizuri." }],
        partOfSpeech: "adjective",
        tags: ["compliment", "people"],
        region: "Nairobi",
    },
    {
        word: "mtiaji",
        slug: "mtiaji",
        definitions: [{ meaning: "A snitch / someone who tells on others", example: "Mtiaji ndiye alimfungulia polisi." }],
        partOfSpeech: "noun",
        tags: ["people", "negative"],
        region: "Nationwide",
    },
    {
        word: "pinji",
        slug: "pinji",
        definitions: [{ meaning: "A thief / pickpocket / phone snatcher", example: "Shika mfuko wako, kuna mapinji hapa." }],
        partOfSpeech: "noun",
        tags: ["people", "crime", "warning"],
        region: "Nairobi",
    },
    {
        word: "mrazi",
        slug: "mrazi",
        definitions: [{ meaning: "A traitor / a secret spoiler / someone who betrays the crew", example: "Yule mrazi alitupa kwa polisi." }],
        partOfSpeech: "noun",
        tags: ["people", "negative", "betrayal"],
        region: "Nationwide",
    },
    {
        word: "bossy",
        slug: "bossy",
        definitions: [{ meaning: "A respected person / a friend or peer. Used as a term of address.", example: "Bossy, nipe mkono hapa." }],
        partOfSpeech: "noun",
        tags: ["people", "respect", "address"],
        region: "Nairobi",
    },

    // ── MONEY ─────────────────────────────────────────────────
    {
        word: "ganji",
        slug: "ganji",
        definitions: [{ meaning: "Money / cash", example: "Siko na ganji saa hii." }],
        partOfSpeech: "noun",
        tags: ["money"],
        region: "Nationwide",
        relatedWords: ["chapaa", "packe", "mukuchu", "doh"],
    },
    {
        word: "chapaa",
        slug: "chapaa",
        definitions: [{ meaning: "Money", example: "Nahitaji chapaa kidogo kukamilisha deal." }],
        partOfSpeech: "noun",
        tags: ["money"],
        region: "Nationwide",
    },
    {
        word: "doh",
        slug: "doh",
        definitions: [{ meaning: "Money / cash (from English 'dough')", example: "Doh iko? Tuweze ku-plan." }],
        partOfSpeech: "noun",
        origin: "From English slang 'dough'",
        tags: ["money"],
        region: "Nationwide",
    },
    {
        word: "packe",
        slug: "packe",
        definitions: [{ meaning: "Money", example: "Una packe? Nikusort na kitu kidogo." }],
        partOfSpeech: "noun",
        tags: ["money", "genz"],
        region: "Nationwide",
    },
    {
        word: "mukuchu",
        slug: "mukuchu",
        definitions: [{ meaning: "Money", example: "Mukuchu ndio inafanya dunia izunguke." }],
        partOfSpeech: "noun",
        tags: ["money", "genz"],
        region: "Nairobi",
    },
    {
        word: "thao",
        slug: "thao",
        definitions: [{ meaning: "One thousand shillings (Ksh. 1,000)", example: "Niambie thao mbili nitarudisha kesho." }],
        partOfSpeech: "noun",
        tags: ["money", "currency"],
        region: "Nationwide",
        relatedWords: ["punch", "rwabe"],
    },
    {
        word: "punch",
        slug: "punch",
        definitions: [{ meaning: "Five hundred shillings (Ksh. 500)", example: "Naomba punch yangu ulianibia." }],
        partOfSpeech: "noun",
        tags: ["money", "currency"],
        region: "Nationwide",
    },
    {
        word: "rwabe",
        slug: "rwabe",
        definitions: [{ meaning: "Two hundred shillings (Ksh. 200)", example: "Nilikuwa na rwabe peke yangu mfukoni." }],
        partOfSpeech: "noun",
        tags: ["money", "currency"],
        region: "Nationwide",
    },
    {
        word: "jongo",
        slug: "jongo",
        definitions: [{ meaning: "One hundred shillings (Ksh. 100)", example: "Nilikula githeri kwa jongo moja." }],
        partOfSpeech: "noun",
        tags: ["money", "currency"],
        region: "Nairobi",
        relatedWords: ["kioo"],
    },
    {
        word: "kioo",
        slug: "kioo",
        definitions: [{ meaning: "One hundred shillings (Ksh. 100)", example: "Gari ya mat ni kioo moja tu." }],
        partOfSpeech: "noun",
        tags: ["money", "currency"],
        region: "Nairobi",
    },
    {
        word: "chuani",
        slug: "chuani",
        definitions: [{ meaning: "Fifty shillings (Ksh. 50)", example: "Nilikuwa na chuani peke yangu." }],
        partOfSpeech: "noun",
        tags: ["money", "currency"],
        region: "Nationwide",
        relatedWords: ["finje"],
    },
    {
        word: "kinde",
        slug: "kinde",
        definitions: [{ meaning: "Ten shillings (Ksh. 10)", example: "Weza kunipa kinde ya credit?" }],
        partOfSpeech: "noun",
        tags: ["money", "currency"],
        region: "Nationwide",
    },
    {
        word: "omoka",
        slug: "omoka",
        definitions: [{ meaning: "To get rich / to make it in life / to come up", example: "Tutaomoka hii year, naenda serious." }],
        partOfSpeech: "verb",
        tags: ["money", "success", "hustle"],
        region: "Nationwide",
    },

    // ── PLACES & LOCATIONS ────────────────────────────────────
    {
        word: "kanairo",
        slug: "kanairo",
        definitions: [{ meaning: "Nairobi City", example: "Kanairo ni ngumu lakini nakipenda." }],
        partOfSpeech: "noun",
        origin: "Popularized by Madocho of Gotta City in 2020, then spread by Trio Mio and Mejja",
        tags: ["places", "nairobi"],
        region: "Nationwide",
    },
    {
        word: "mta",
        slug: "mta",
        definitions: [{ meaning: "Home / where you stay", example: "Naenda mta, nimechoka." }],
        partOfSpeech: "noun",
        tags: ["places", "home"],
        region: "Nationwide",
        relatedWords: ["rotejo", "balaluu"],
    },
    {
        word: "rotejo",
        slug: "rotejo",
        definitions: [{ meaning: "Your house / home", example: "Kaa rotejo leo, hali ya hewa ni mbaya." }],
        partOfSpeech: "noun",
        tags: ["places", "home"],
        region: "Nairobi",
    },
    {
        word: "balaluu",
        slug: "balaluu",
        definitions: [{ meaning: "Home", example: "Tunaenda balaluu saa tatu usiku." }],
        partOfSpeech: "noun",
        origin: "Introduced by Wakadinali in their 2022 song 'Balaluu'",
        tags: ["places", "home", "wakadinali"],
        region: "Nationwide",
    },
    {
        word: "mushatha",
        slug: "mushatha",
        definitions: [{ meaning: "Upcountry / the village / rural areas", example: "Nilikuwa mushatha over Christmas, nilifurahi sana." }],
        partOfSpeech: "noun",
        tags: ["places", "village"],
        region: "Nationwide",
        relatedWords: ["ocha"],
    },
    {
        word: "oyole",
        slug: "oyole",
        definitions: [{ meaning: "Kayole estate in Nairobi", example: "Natoka Oyole, Eastlands represent." }],
        partOfSpeech: "noun",
        tags: ["places", "eastlands", "nairobi"],
        region: "Nairobi",
    },
    {
        word: "zabe",
        slug: "zabe",
        definitions: [{ meaning: "A hangout spot / a place where friends chill", example: "Zabe yetu iko kwa corner ya mtaa." }],
        partOfSpeech: "noun",
        tags: ["places", "social"],
        region: "Nairobi",
    },
    {
        word: "choche",
        slug: "choche",
        definitions: [{ meaning: "A secret hideout / a hidden place", example: "Wanaenda choche zao baada ya job." }],
        partOfSpeech: "noun",
        tags: ["places", "secret"],
        region: "Nairobi",
    },
    {
        word: "wathii",
        slug: "wathii",
        definitions: [{ meaning: "A market / specifically where you buy clothes (like Gikomba)", example: "Tunaenda wathii kesho kupata mitumba." }],
        partOfSpeech: "noun",
        tags: ["places", "shopping"],
        region: "Nairobi",
    },
    {
        word: "bez",
        slug: "bez",
        definitions: [{ meaning: "A spot in the hood where young people hang out", example: "Nitakupata kwa bez baadaye." }],
        partOfSpeech: "noun",
        tags: ["places", "social", "hood"],
        region: "Nairobi",
    },

    // ── TRANSPORT ─────────────────────────────────────────────
    {
        word: "mathree",
        slug: "mathree",
        definitions: [{ meaning: "A Kenyan matatu / public minibus", example: "Nimechelewa, mathree ilikuwa imejaa." }],
        partOfSpeech: "noun",
        origin: "Corruption of 'matatu' (public minibus), referencing the '3' in matatu",
        tags: ["transport", "everyday"],
        region: "Nationwide",
    },
    {
        word: "mrenga",
        slug: "mrenga",
        definitions: [{ meaning: "A car", example: "Ameblock na mrenga yake mpya." }],
        partOfSpeech: "noun",
        tags: ["transport", "cars"],
        region: "Nationwide",
    },
    {
        word: "jav",
        slug: "jav",
        definitions: [{ meaning: "To commute by public transport / a matatu or bus", example: "Naenda jav mpaka town, tuweze kuonana." }],
        partOfSpeech: "verb",
        origin: "From KBS (Kenya Bus Service)",
        tags: ["transport", "everyday"],
        region: "Nairobi",
    },

    // ── LIFESTYLE & SLANG ──────────────────────────────────────
    {
        word: "warena",
        slug: "warena",
        definitions: [{ meaning: "A flashy lifestyle / fire / something that is lit", example: "Vaa vizuri, warena iwe na level." }],
        partOfSpeech: "noun",
        origin: "Derived from Sheng 'Nare' meaning fire. Popularized by Mbogi Genje and Khaligraph Jones in 2021",
        tags: ["lifestyle", "fashion", "music"],
        region: "Nationwide",
    },
    {
        word: "luku",
        slug: "luku",
        definitions: [{ meaning: "A fashionable, elegant outfit or appearance", example: "Luku yake leo ni moto kabisa." }],
        partOfSpeech: "noun",
        origin: "From English 'look'",
        tags: ["fashion", "lifestyle"],
        region: "Nationwide",
    },
    {
        word: "kiki",
        slug: "kiki",
        definitions: [{ meaning: "Clout / fame / social media attention", example: "Anatafuta kiki tu, hakuna substance." }],
        partOfSpeech: "noun",
        tags: ["social-media", "lifestyle", "genz"],
        region: "Nationwide",
    },
    {
        word: "cheza-chini",
        slug: "cheza-chini",
        definitions: [{ meaning: "Playing it cool / to chill out / lay low", example: "Cheza chini bana, polisi wako karibu." }],
        partOfSpeech: "expression",
        origin: "Swahili — 'play low/below'",
        tags: ["lifestyle", "warning", "advice"],
        region: "Nationwide",
    },
    {
        word: "uradi",
        slug: "uradi",
        definitions: [{ meaning: "The way forward / an interesting plan / a good move", example: "Hii business idea ndio uradi, tutaomoka." }],
        partOfSpeech: "noun",
        tags: ["lifestyle", "plans", "hustle"],
        region: "Nationwide",
    },
    {
        word: "imbo",
        slug: "imbo",
        definitions: [{ meaning: "Something fake / not original", example: "Hii sneakers ni imbo, si original." }],
        partOfSpeech: "adjective",
        tags: ["lifestyle", "fashion", "fake"],
        region: "Nationwide",
    },
    {
        word: "elchapo",
        slug: "elchapo",
        definitions: [{ meaning: "Someone extraordinary / someone who is on a different level", example: "Yule msee ni elchapo wa coding, anajua kila kitu." }],
        partOfSpeech: "adjective",
        origin: "Named after El Chapo, the Mexican drug lord, implying someone who operates at a higher level",
        tags: ["compliment", "genz"],
        region: "Nationwide",
    },
    {
        word: "vayolens",
        slug: "vayolens",
        definitions: [{ meaning: "Violence / chaos / something intense is about to happen", example: "Waacha vayolens, tutapatana vizuri." }],
        partOfSpeech: "noun",
        origin: "Sheng corruption of English 'violence', popularized by social media",
        tags: ["lifestyle", "conflict", "social-media"],
        region: "Nationwide",
    },
    {
        word: "kitawaramba",
        slug: "kitawaramba",
        definitions: [{ meaning: "Something will backfire on you / karma is coming", example: "Endelea kufanya hivyo, kitawaramba." }],
        partOfSpeech: "expression",
        origin: "Went viral in 2023 following the Shakahola massacre coverage",
        tags: ["expression", "karma", "warning"],
        region: "Nationwide",
    },
    {
        word: "wantam",
        slug: "wantam",
        definitions: [{ meaning: "One term / briefly / for just a short period", example: "Wantam tu, saa hii niko busy." }],
        partOfSpeech: "expression",
        origin: "Popularized by political discourse around Riggy G and the DCP party",
        tags: ["expression", "genz"],
        region: "Nationwide",
    },
    {
        word: "kasongo",
        slug: "kasongo",
        definitions: [{ meaning: "Context-dependent — can mean a situation, a state of affairs, or a person who is in a bad spot", example: "Hali yake ni kasongo saa hii." }],
        partOfSpeech: "noun",
        tags: ["genz", "expression"],
        region: "Nationwide",
    },
    {
        word: "mraa",
        slug: "mraa",
        definitions: [{ meaning: "Your hustle / the work you do / also can mean the area you stay in", example: "Mraa wangu ni graphics design, naipenda." }],
        partOfSpeech: "noun",
        tags: ["hustle", "work", "everyday"],
        region: "Nairobi",
    },
    {
        word: "mboka",
        slug: "mboka",
        definitions: [{ meaning: "A job / work / employment", example: "Bado natafuta mboka, iko ngumu." }],
        partOfSpeech: "noun",
        tags: ["work", "hustle"],
        region: "Nationwide",
    },
    {
        word: "kaveve-kazoze",
        slug: "kaveve-kazoze",
        definitions: [{ meaning: "Getting aggressively high on khat / indulging intensely in miraa", example: "Waliamua kaveve kazoze usiku kucha." }],
        partOfSpeech: "expression",
        origin: "Coined by Kenyan gengetone rapper Ngesh of Spider Clan. Kaveve from 'veve' (khat) + kazoze from 'zoza' (to get aggressive)",
        tags: ["substances", "khat", "gengetone"],
        region: "Nationwide",
    },
    {
        word: "siku-zombo",
        slug: "siku-zombo",
        definitions: [{ meaning: "Everyday / day in, day out", example: "Anafanya kazi siku zombo bila kupumzika." }],
        partOfSpeech: "expression",
        origin: "Popularized by Mziza Family in their track 'Ni God Siku Zombo'",
        tags: ["expression", "everyday", "music"],
        region: "Nationwide",
    },
    {
        word: "kirende",
        slug: "kirende",
        definitions: [{ meaning: "A big multitude / a large crowd of people", example: "Kirende iliingia stadium, ilikuwa moto." }],
        partOfSpeech: "noun",
        origin: "Borrowed from Kikuyu. Popularized by Spider-Clan in 2023",
        tags: ["people", "crowd"],
        region: "Nationwide",
    },

    // ── ACTIONS & VERBS ───────────────────────────────────────
    {
        word: "ngasha",
        slug: "ngasha",
        definitions: [{ meaning: "To take a shower / to bathe", example: "Niende ni-ngashe kwanza kabla ya kuenda." }],
        partOfSpeech: "verb",
        tags: ["everyday", "actions"],
        region: "Nationwide",
    },
    {
        word: "shera",
        slug: "shera",
        definitions: [{ meaning: "To dance", example: "Watu wanashera kwa show usiku." }],
        partOfSpeech: "verb",
        origin: "Derived from the Miondoko dance style",
        tags: ["dance", "entertainment"],
        region: "Nationwide",
    },
    {
        word: "bant",
        slug: "bant",
        definitions: [{ meaning: "To make a mistake / to mess up", example: "Umebant kubwa — ulisema nini mbele ya boss?" }],
        partOfSpeech: "verb",
        tags: ["actions", "mistake"],
        region: "Nationwide",
        relatedWords: ["choma"],
    },
    {
        word: "malo",
        slug: "malo",
        definitions: [{ meaning: "To eat / to finish something", example: "Tumalo chakula kwanza halafu tuongee." }],
        partOfSpeech: "verb",
        tags: ["actions", "food", "everyday"],
        region: "Nationwide",
    },
    {
        word: "ganda",
        slug: "ganda",
        definitions: [
            { meaning: "To die / to beat someone up", example: "Msee aliambia atamganda kwa mtaa." },
        ],
        partOfSpeech: "verb",
        tags: ["actions", "conflict"],
        region: "Nationwide",
    },
    {
        word: "purura",
        slug: "purura",
        definitions: [{ meaning: "To play / to fool around / to be a player (in relationships)", example: "Anajifanya anataka serious lakini anakupurura tu." }],
        partOfSpeech: "verb",
        tags: ["actions", "relationships"],
        region: "Nairobi",
    },
    {
        word: "zoza",
        slug: "zoza",
        definitions: [{ meaning: "To start trouble / to provoke", example: "Usije ukamzoza, ni mtu wa hatari." }],
        partOfSpeech: "verb",
        tags: ["actions", "conflict"],
        region: "Nationwide",
    },
    {
        word: "banja",
        slug: "banja",
        definitions: [{ meaning: "To talk / to speak / to have a conversation", example: "Tukuje tu-banje — kuna mambo mengi ya kushughulikia." }],
        partOfSpeech: "verb",
        tags: ["actions", "communication"],
        region: "Nairobi",
    },
    {
        word: "muoket",
        slug: "muoket",
        definitions: [{ meaning: "To come over / to arrive", example: "Muoket haraka, tuko tayari." }],
        partOfSpeech: "verb",
        tags: ["actions", "movement"],
        region: "Nairobi",
    },
    {
        word: "vuva",
        slug: "vuva",
        definitions: [{ meaning: "To smoke / meditate over weed / to take marijuana", example: "Wanaenda kuvuva mahali pa siri." }],
        partOfSpeech: "verb",
        tags: ["substances", "weed"],
        region: "Nationwide",
    },
    {
        word: "wamocho",
        slug: "wamocho",
        definitions: [{ meaning: "To take alcohol / to drink", example: "Tuende tuwamoche kidogo, ni weekend." }],
        partOfSpeech: "verb",
        tags: ["substances", "alcohol"],
        region: "Nairobi",
    },
    {
        word: "kudonjo",
        slug: "kudonjo",
        definitions: [{ meaning: "To come / to arrive. Also used to mean something interesting happening", example: "Kudonjo hapa jioni, tutaenda pamoja." }],
        partOfSpeech: "verb",
        tags: ["actions", "movement"],
        region: "Nationwide",
    },
    {
        word: "gwaya",
        slug: "gwaya",
        definitions: [{ meaning: "To fear / to be scared of something", example: "Usigwaye, tutatoka hali yoyote." }],
        partOfSpeech: "verb",
        tags: ["emotions", "actions"],
        region: "Nairobi",
    },
    {
        word: "gotha-tena",
        slug: "gotha-tena",
        definitions: [{ meaning: "Pull it up again / replay that / do it again", example: "Gotha tena ile track, ilikuwa hard." }],
        partOfSpeech: "expression",
        origin: "From Kikuyu. Popularized by Breeder LW in 'Dedi Dedilee', originally used by Mbogi Nare reggae crew",
        tags: ["expression", "music", "genz"],
        region: "Nationwide",
    },

    // ── POLICE & AUTHORITY ────────────────────────────────────
    {
        word: "karao",
        slug: "karao",
        definitions: [{ meaning: "A police officer", example: "Cheza chini, karao wako hapa." }],
        partOfSpeech: "noun",
        tags: ["police", "authority", "warning"],
        region: "Nationwide",
        relatedWords: ["mbaru", "saigon", "hessy"],
    },
    {
        word: "mbaru",
        slug: "mbaru",
        definitions: [{ meaning: "Police officers", example: "Mbaru wamejaa area hii, kuwa careful." }],
        partOfSpeech: "noun",
        tags: ["police", "authority"],
        region: "Nairobi",
    },
    {
        word: "saigon",
        slug: "saigon",
        definitions: [{ meaning: "A police officer", example: "Saigon yule anakuangalia, ingia ndani." }],
        partOfSpeech: "noun",
        tags: ["police", "authority"],
        region: "Nairobi",
    },
    {
        word: "hessy",
        slug: "hessy",
        definitions: [{ meaning: "A police officer", example: "Hessy wamevaa civi lakini tunawajua." }],
        partOfSpeech: "noun",
        tags: ["police", "authority"],
        region: "Nairobi",
    },

    // ── TECHNOLOGY & PHONES ───────────────────────────────────
    {
        word: "thiang",
        slug: "thiang",
        definitions: [{ meaning: "A smartphone / a fancy or expensive phone", example: "Amechomeka thiang' mpya, Samsung S24." }],
        partOfSpeech: "noun",
        tags: ["technology", "phones"],
        region: "Nairobi",
        relatedWords: ["tonje"],
    },
    {
        word: "tonje",
        slug: "tonje",
        definitions: [{ meaning: "A mobile phone", example: "Tonje yangu battery imekufa." }],
        partOfSpeech: "noun",
        tags: ["technology", "phones"],
        region: "Nationwide",
    },
    {
        word: "tulutulu",
        slug: "tulutulu",
        definitions: [{ meaning: "An old school phone / feature phone / not a smartphone (Mulika Mwizi)", example: "Bado ana tulutulu — mwambie apgrade." }],
        partOfSpeech: "noun",
        tags: ["technology", "phones", "old"],
        region: "Nationwide",
    },
    {
        word: "mbulu",
        slug: "mbulu",
        definitions: [{ meaning: "A television / TV", example: "Mbulu ya hii nyumba ni kubwa sana." }],
        partOfSpeech: "noun",
        tags: ["technology", "entertainment"],
        region: "Nairobi",
    },
    {
        word: "m-sape",
        slug: "m-sape",
        definitions: [{ meaning: "M-PESA / mobile money transfer", example: "Nit-umie m-sape, sina cash mkononi." }],
        partOfSpeech: "noun",
        origin: "Coined by Sewersydaa in the song 'Cry Baby'",
        tags: ["technology", "money", "mpesa"],
        region: "Nationwide",
    },
    {
        word: "wanjapi",
        slug: "wanjapi",
        definitions: [{ meaning: "A photo / photograph / picture", example: "Pigana wanjapi, tutaweka stories." }],
        partOfSpeech: "noun",
        tags: ["technology", "social-media"],
        region: "Nairobi",
    },

    // ── SUBSTANCES ────────────────────────────────────────────
    {
        word: "jaba",
        slug: "jaba",
        definitions: [{ meaning: "Khat / Miraa (a stimulant plant chewed in East Africa)", example: "Wanakaa kwa kaveve zao wakichew jaba." }],
        partOfSpeech: "noun",
        tags: ["substances", "khat"],
        region: "Nationwide",
        relatedWords: ["veve", "mavela", "gwethe"],
    },
    {
        word: "kolo",
        slug: "kolo",
        definitions: [{ meaning: "Weed / marijuana / cannabis", example: "Moshi wa kolo unatoka kwa chumba." }],
        partOfSpeech: "noun",
        tags: ["substances", "weed"],
        region: "Nairobi",
        relatedWords: ["kindukulu", "ngusu", "ndom"],
    },
    {
        word: "kindukulu",
        slug: "kindukulu",
        definitions: [{ meaning: "Marijuana / weed / cannabis sativa", example: "Walikuwa na kindukulu kwa mfuko." }],
        partOfSpeech: "noun",
        tags: ["substances", "weed"],
        region: "Nairobi",
    },
    {
        word: "mzinga",
        slug: "mzinga",
        definitions: [{ meaning: "A full new bottle of alcohol", example: "Walitoa mzinga ya Jameson waka-celebrate." }],
        partOfSpeech: "noun",
        tags: ["substances", "alcohol", "celebration"],
        region: "Nationwide",
    },
    {
        word: "chingri",
        slug: "chingri",
        definitions: [{ meaning: "Alcohol", example: "Chingri inaingia, akili inaenda." }],
        partOfSpeech: "noun",
        tags: ["substances", "alcohol"],
        region: "Nairobi",
    },
    {
        word: "makali",
        slug: "makali",
        definitions: [{ meaning: "Gin / strong alcoholic drinks", example: "Hakuna pesa ya makali, tutakunywa bia tu." }],
        partOfSpeech: "noun",
        tags: ["substances", "alcohol"],
        region: "Nationwide",
    },
    {
        word: "nyongi",
        slug: "nyongi",
        definitions: [{ meaning: "A small, short blunt that burns your hands or lips when smoked", example: "Nyongi inabaki tu, kaa inauma vidole." }],
        partOfSpeech: "noun",
        tags: ["substances", "weed"],
        region: "Nairobi",
    },
    {
        word: "shada",
        slug: "shada",
        definitions: [{ meaning: "A roll of weed / a joint", example: "Walifunga shada moja kwa geto." }],
        partOfSpeech: "noun",
        tags: ["substances", "weed"],
        region: "Nairobi",
    },

    // ── MISC EXPRESSIONS ──────────────────────────────────────
    {
        word: "kimbokta",
        slug: "kimbokta",
        definitions: [{ meaning: "A long time ago / back in the day", example: "Hiyo ilikuwa kimbokta, msiseme tena." }],
        partOfSpeech: "expression",
        tags: ["time", "expression"],
        region: "Nationwide",
    },
    {
        word: "mbichwa",
        slug: "mbichwa",
        definitions: [{ meaning: "Something new / fresh / just released", example: "Vaa mbichwa leo, tunaenda event." }],
        partOfSpeech: "adjective",
        origin: "From Swahili 'mbichi' meaning raw/unripe/new",
        tags: ["fashion", "new", "everyday"],
        region: "Nationwide",
    },
    {
        word: "kimonyoski",
        slug: "kimonyoski",
        definitions: [{ meaning: "A group of people who share common interests / a clique", example: "Kimonyoski chake ni watu wa art peke yao." }],
        partOfSpeech: "noun",
        tags: ["people", "social", "crew"],
        region: "Nairobi",
    },
    {
        word: "manambling",
        slug: "manambling",
        definitions: [{ meaning: "Haters / people who are jealous or negative", example: "Manambling wataona, bado tunafanya kazi." }],
        partOfSpeech: "noun",
        tags: ["people", "haters", "social"],
        region: "Nationwide",
    },
    {
        word: "thutha",
        slug: "thutha",
        definitions: [{ meaning: "Behind / at the back", example: "Kaa thutha ya gari, mbele imejaa." }],
        partOfSpeech: "adverb",
        tags: ["direction", "everyday"],
        region: "Nationwide",
    },
    {
        word: "tispo",
        slug: "tispo",
        definitions: [{ meaning: "Sports", example: "Yeye ni mzuri sana kwa tispo ya basketball." }],
        partOfSpeech: "noun",
        origin: "Corruption of English 'sports'",
        tags: ["sports", "everyday"],
        region: "Nationwide",
    },
    {
        word: "ndula",
        slug: "ndula",
        definitions: [{ meaning: "Shoes / sneakers", example: "Ndula zake ni safi, ni Jordans za kweli." }],
        partOfSpeech: "noun",
        tags: ["fashion", "clothing"],
        region: "Nationwide",
    },
    {
        word: "riba",
        slug: "riba",
        definitions: [{ meaning: "A story / gossip / news", example: "Niambie riba, nini kimetokea?" }],
        partOfSpeech: "noun",
        tags: ["communication", "gossip"],
        region: "Nairobi",
    },
    {
        word: "dang",
        slug: "dang",
        definitions: [{ meaning: "Danguch / an outgoing person, especially a free-spirited or bold woman", example: "Yeye ni dang, hawezi kukaa nyumbani." }],
        partOfSpeech: "noun",
        tags: ["people", "personality"],
        region: "Nairobi",
    },
    {
        word: "kidi",
        slug: "kidi",
        definitions: [{ meaning: "A dangerous weapon, especially a gun", example: "Walisikia ana kidi, wote walikimbia." }],
        partOfSpeech: "noun",
        tags: ["weapons", "danger", "street"],
        region: "Nairobi",
    },
    {
        word: "mbleina",
        slug: "mbleina",
        definitions: [{ meaning: "Someone absent-minded / a clueless person / someone who knows nothing", example: "Huyu ni mbleina, hakujua hata bei ya gari." }],
        partOfSpeech: "noun",
        tags: ["people", "insult"],
        region: "Nairobi",
    },
    {
        word: "mbuku",
        slug: "mbuku",
        definitions: [{ meaning: "A book", example: "Soma mbuku yako badala ya kushinda mtaani." }],
        partOfSpeech: "noun",
        origin: "Corruption of English 'book'",
        tags: ["education", "everyday"],
        region: "Nationwide",
    },
    {
        word: "mode",
        slug: "mode",
        definitions: [{ meaning: "A teacher", example: "Mode wetu wa hesabu ni mkali sana." }],
        partOfSpeech: "noun",
        tags: ["education", "school"],
        region: "Nairobi",
    },
    {
        word: "jipin",
        slug: "jipin",
        definitions: [{ meaning: "To protect yourself / to get necessary protection", example: "Jipin vizuri unapoenda area hiyo usiku." }],
        partOfSpeech: "verb",
        tags: ["safety", "advice"],
        region: "Nairobi",
    },
    {
        word: "peng",
        slug: "peng",
        definitions: [{ meaning: "A very attractive girl / something great or fine", example: "Yule dem ni peng kabisa." }],
        partOfSpeech: "adjective",
        origin: "Borrowed from UK slang 'peng'",
        tags: ["compliment", "girls", "genz"],
        region: "Nationwide",
    },
    {
        word: "stoko",
        slug: "stoko",
        definitions: [{ meaning: "Stock / inventory / supply of something", example: "Stoko imeisha, tutaorder tena kesho." }],
        partOfSpeech: "noun",
        tags: ["business", "everyday"],
        region: "Nationwide",
    },
    {
        word: "njoti",
        slug: "njoti",
        definitions: [{ meaning: "Groundnuts / peanuts", example: "Nunua njoti kwa hiyo mama pale, ni tamu." }],
        partOfSpeech: "noun",
        tags: ["food", "snacks"],
        region: "Nairobi",
    },
    {
        word: "mnisa",
        slug: "mnisa",
        definitions: [{ meaning: "An artist / musician / creative", example: "Yeye ni mnisa wa kweli, ana talent." }],
        partOfSpeech: "noun",
        origin: "Popularized by ThirtyFourBrick",
        tags: ["music", "art", "people"],
        region: "Nationwide",
    },
    {
        word: "mziza",
        slug: "mziza",
        definitions: [{ meaning: "A parent", example: "Mziza wangu alinipa greenlight ya kwenda event." }],
        partOfSpeech: "noun",
        origin: "From Swahili 'mzazi'. Popularized by Scar Mkadinali of Wakadinali",
        tags: ["family", "people"],
        region: "Nationwide",
    },
    {
        word: "njigri",
        slug: "njigri",
        definitions: [{ meaning: "A bicycle", example: "Anakuja kwa njigri kila siku shuleni." }],
        partOfSpeech: "noun",
        tags: ["transport", "everyday"],
        region: "Nationwide",
    },
    {
        word: "kortko",
        slug: "kortko",
        definitions: [{ meaning: "A court / basketball court / football pitch", example: "Tutaonana kortko jioni ya leo." }],
        partOfSpeech: "noun",
        origin: "Corruption of English 'court'",
        tags: ["sports", "places"],
        region: "Nairobi",
    },
    {
        word: "nyonginyo",
        slug: "nyonginyo",
        definitions: [{ meaning: "Socks", example: "Nyonginyo zake ni clean, zinaenda vizuri na sneakers." }],
        partOfSpeech: "noun",
        tags: ["fashion", "clothing"],
        region: "Nairobi",
    },
    {
        word: "m-sape",
        slug: "msape",
        definitions: [{ meaning: "M-PESA / mobile money", example: "Nit-umie m-sape, ATM haikufanya kazi." }],
        partOfSpeech: "noun",
        tags: ["money", "technology", "mpesa"],
        region: "Nationwide",
    },
];

// ── Runner ─────────────────────────────────────────────────────
async function seed() {
    const uri = process.env.MONGODB_URI;
    if (!uri) {
        console.error("❌  MONGODB_URI not found in .env.local");
        process.exit(1);
    }

    console.log("🔌  Connecting to MongoDB...");
    await mongoose.connect(uri);
    console.log("✅  Connected!\n");

    console.log("🌱  Seeding words...");
    let added = 0;
    let skipped = 0;

    for (const word of words) {
        try {
            await Word.findOneAndUpdate(
                { slug: word.slug },
                { $setOnInsert: word },
                { upsert: true, returnDocument: 'before' }
            );
            added++;
            console.log(`   ✔  ${word.word}`);
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
        } catch (err: any) {
            console.warn(`   ⚠  Skipped "${word.word}": ${err.message}`);
            skipped++;
        }
    }

    console.log(`\n🎉  Done! ${added} words processed, ${skipped} skipped.`);
    await mongoose.disconnect();
    process.exit(0);
}

seed().catch((err) => {
    console.error("💥  Seed failed:", err);
    process.exit(1);
});